// GENERATED by packages/design-system/scripts/generate-tokens.mjs — do not edit by hand.
// Source: docs/strata-design-tokens.json. Run `pnpm tokens` to regenerate.

export type ConfidenceLabel = "HIGH" | "MEDIUM" | "LOW";

/** Confidence is presentation DATA, not a color token (Strata rule). */
export const confidencePolicy = {
  high: { threshold: 0.85, label: "HIGH", segments: 3 },
  medium: { threshold: 0.6, label: "MEDIUM", segments: 2 },
  low: { threshold: 0, label: "LOW", segments: 1 },
} as const;

/** Resolve a 0..1 confidence decimal to its categorical label. */
export function confidenceLabel(value: number): ConfidenceLabel {
  if (value >= confidencePolicy.high.threshold) return "HIGH";
  if (value >= confidencePolicy.medium.threshold) return "MEDIUM";
  return "LOW";
}

export const confidenceSegments: Record<ConfidenceLabel, number> = {
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
};

export const NAMESPACES = [
  "BUSINESS",
  "ENTERPRISE",
  "TECHNOLOGY",
  "OSS",
  "DEPLOYMENT",
  "INTELLIGENCE",
] as const;
export type Namespace = (typeof NAMESPACES)[number];

/** Two-letter badge codes + domain color family per namespace (design language §domain badge). */
export const domainMeta: Record<Namespace, { code: string; family: string }> = {
  BUSINESS: { code: "BIZ", family: "business" },
  ENTERPRISE: { code: "ENT", family: "enterprise" },
  TECHNOLOGY: { code: "TEC", family: "enterprise" },
  OSS: { code: "OSS", family: "oss" },
  DEPLOYMENT: { code: "DEP", family: "enterprise" },
  INTELLIGENCE: { code: "INT", family: "intelligence" },
};
