#!/usr/bin/env node
/**
 * Strata token generator.
 * Source of truth: docs/strata-design-tokens.json (DTCG format).
 * Emits:
 *   - src/tokens/tokens.css  — CSS custom properties (light default + dark overrides)
 *   - src/tokens/tokens.ts   — typed token references + confidence policy (as DATA, not color)
 *
 * Implements the impl-plan P2 fix:
 *   - `text.*` and `surface.*` are resolved per-mode (light on :root, dark under
 *     [data-theme="dark"] and prefers-color-scheme:dark) so `text.primary` is never mode-ambiguous.
 *   - `confidence` is emitted as data (thresholds/labels/segments), never as a color token.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../../..");
const SRC = resolve(repoRoot, "docs/strata-design-tokens.json");
const OUT_DIR = resolve(__dirname, "../src/tokens");

const tokens = JSON.parse(readFileSync(SRC, "utf8"));

/** flatten a nested {k:{$value}} object into [ [dashed-path, value] ] */
function flattenColors(obj, prefix, out) {
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === "object" && "$value" in v) {
      out.push([`${prefix}-${k}`, v.$value]);
    } else if (v && typeof v === "object") {
      flattenColors(v, `${prefix}-${k}`, out);
    }
  }
  return out;
}

const modeIndependent = [];
const c = tokens.color;

// Domain ramps + danger are mode-independent (chosen to work on both surfaces).
flattenColors(c.domain, "color-domain", modeIndependent);
flattenColors(c.signal, "color-signal", modeIndependent);

// Spacing / radius / motion / borders are mode-independent.
for (const [k, v] of Object.entries(tokens.spacing)) modeIndependent.push([`space-${k}`, v.$value]);
for (const [k, v] of Object.entries(tokens.radius)) modeIndependent.push([`radius-${k}`, v.$value]);
for (const [k, v] of Object.entries(tokens.motion)) modeIndependent.push([`motion-${k}`, v.$value]);
modeIndependent.push(["border-hairline", tokens.border.hairline.$value]);

// Typography families + scale.
modeIndependent.push(["font-narrative", `"${tokens.typography.family.narrative.$value}", ui-sans-serif, system-ui, sans-serif`]);
modeIndependent.push(["font-evidence", `"${tokens.typography.family.evidence.$value}", ui-monospace, "SFMono-Regular", monospace`]);
for (const [name, v] of Object.entries(tokens.typography.scale)) {
  const t = v.$value;
  modeIndependent.push([`type-${name}-size`, t.fontSize]);
  modeIndependent.push([`type-${name}-line`, t.lineHeight]);
  modeIndependent.push([`type-${name}-weight`, String(t.fontWeight)]);
}

// Elevation → box-shadow strings.
modeIndependent.push(["elevation-flat", "none"]);
const raised = tokens.elevation.raised.$value;
modeIndependent.push(["elevation-raised", `${raised.x} ${raised.y} ${raised.blur} ${raised.spread} ${raised.color}`]);

// Mode-dependent: surface + text, resolved per mode.
function modeVars(mode) {
  const out = [];
  for (const [k, v] of Object.entries(c.surface[mode])) out.push([`surface-${k}`, v.$value]);
  for (const [k, v] of Object.entries(c.text[mode])) out.push([`text-${k}`, v.$value]);
  return out;
}
const lightVars = modeVars("light");
const darkVars = modeVars("dark");

const emit = (pairs, indent = "  ") => pairs.map(([k, val]) => `${indent}--sg-${k}: ${val};`).join("\n");

const css = `/* GENERATED by packages/design-system/scripts/generate-tokens.mjs — do not edit by hand.
   Source: docs/strata-design-tokens.json. Run \`pnpm tokens\` to regenerate. */

:root {
${emit(modeIndependent)}

  /* surface + text: light is the default mode */
${emit(lightVars)}
}

/* Explicit dark selection wins in both directions. */
:root[data-theme="dark"] {
${emit(darkVars)}
}

/* System dark, unless the user forced light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${emit(darkVars, "    ")}
  }
}
`;

// Confidence as DATA (never a color). LOW carries the one danger accent.
const conf = tokens.confidence;
const ts = `// GENERATED by packages/design-system/scripts/generate-tokens.mjs — do not edit by hand.
// Source: docs/strata-design-tokens.json. Run \`pnpm tokens\` to regenerate.

export type ConfidenceLabel = "HIGH" | "MEDIUM" | "LOW";

/** Confidence is presentation DATA, not a color token (Strata rule). */
export const confidencePolicy = {
  high: { threshold: ${conf.high.threshold}, label: "HIGH", segments: 3 },
  medium: { threshold: ${conf.medium.threshold}, label: "MEDIUM", segments: 2 },
  low: { threshold: ${conf.low.threshold}, label: "LOW", segments: 1 },
} as const;

/** Resolve a 0..1 confidence decimal to its categorical label. */
export function confidenceLabel(value: number): ConfidenceLabel {
  if (value >= confidencePolicy.high.threshold) return "HIGH";
  if (value >= confidencePolicy.medium.threshold) return "MEDIUM";
  return "LOW";
}

export const confidenceSegments: Record<ConfidenceLabel, number> = {
  HIGH: 3,
  MEDIUM: 2,
  LOW: 1,
};

export const NAMESPACES = [
  "BUSINESS",
  "ENTERPRISE",
  "TECHNOLOGY",
  "OSS",
  "DEPLOYMENT",
  "INTELLIGENCE",
] as const;
export type Namespace = (typeof NAMESPACES)[number];

/** Two-letter badge codes + domain color family per namespace (design language §domain badge). */
export const domainMeta: Record<Namespace, { code: string; family: string }> = {
  BUSINESS: { code: "BIZ", family: "business" },
  ENTERPRISE: { code: "ENT", family: "enterprise" },
  TECHNOLOGY: { code: "TEC", family: "enterprise" },
  OSS: { code: "OSS", family: "oss" },
  DEPLOYMENT: { code: "DEP", family: "enterprise" },
  INTELLIGENCE: { code: "INT", family: "intelligence" },
};
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(resolve(OUT_DIR, "tokens.css"), css);
writeFileSync(resolve(OUT_DIR, "tokens.ts"), ts);
console.log(`Strata tokens generated → ${OUT_DIR}/{tokens.css,tokens.ts}`);
console.log(`  ${modeIndependent.length} mode-independent vars, ${lightVars.length} per-mode vars.`);
