// Generated by scripts/generate_contract_types.mjs from the canonical OpenAPI document.
// Do not edit by hand. Run `pnpm contracts:generate`.

export interface AIProviderConfiguration {
  contract_version?: "1.0.0";
  enabled?: boolean;
  enrichment_status?: "DISABLED" | "READY" | "QUEUED" | "RUNNING" | "ACTIVE" | "DEGRADED";
  failed_enrichment_jobs?: number;
  key_configured?: boolean;
  key_fingerprint?: string | null;
  last_enrichment_at?: string | null;
  last_error?: string | null;
  model?: string;
  pending_enrichment_jobs?: number;
  provider: "openrouter" | "openai" | "anthropic";
  running_enrichment_jobs?: number;
  test_status?: "NOT_TESTED" | "SUCCEEDED" | "FAILED";
  tested_at?: string | null;
  updated_at?: string | null;
  updated_by?: string | null;
}

export interface AIProviderConfigurationUpdateRequest {
  api_key?: string | null;
  enabled?: boolean;
  model?: string;
  provider: "openrouter" | "openai" | "anthropic";
}

export interface AIProviderConnectionTest {
  contract_version?: "1.0.0";
  models?: Array<string>;
  provider: "openrouter" | "openai" | "anthropic";
  status?: "SUCCEEDED";
}

export interface ApplicationComponentDependencyHierarchy {
  component_path: string;
  dependencies: Array<ApplicationDependencyNode>;
  truncated?: boolean;
}

export interface ApplicationDependencyNode {
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dependency_relation?: string | null;
  depth: number;
  direct: boolean;
  parent_technology_id?: string | null;
  relationship: string;
  requirement?: string | null;
  scope?: string | null;
  technology: EntitySummary;
}

export interface ApplicationDetail {
  application: EntitySummary;
  assessments: Array<AssessmentSummary>;
  business_context: Array<EntitySummary>;
  contract_version?: "1.0.0";
  dependency_hierarchies?: Array<ApplicationRepositoryDependencyHierarchy>;
  deployments: Array<EntitySummary>;
  freshness: Freshness;
  recommendations: Array<RecommendationSummary>;
  repositories: Array<EntitySummary>;
  technologies: Array<EntitySummary>;
  technology_groups: Array<ApplicationTechnologyGroup>;
}

export interface ApplicationRepositoryDependencyHierarchy {
  components: Array<ApplicationComponentDependencyHierarchy>;
  repository: EntitySummary;
}

export interface ApplicationTechnologyFunction {
  function: TaxonomySummary;
  technologies: Array<ApplicationTechnologyUsage>;
}

export interface ApplicationTechnologyGroup {
  domain: TaxonomySummary;
  functions: Array<ApplicationTechnologyFunction>;
}

export interface ApplicationTechnologyUsage {
  category?: TaxonomySummary | null;
  citations: Array<Citation>;
  classification: "CURATED" | "CATALOG_MATCH" | "UNCLASSIFIED";
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  technology: EntitySummary;
}

export interface AskRequest {
  context_entity_ids?: Array<string> | null;
  question: string;
}

export interface AskResponse {
  citations: Array<Citation>;
  contract_version?: "1.0.0";
  graph_highlight?: GraphNeighborhood | null;
  result_kind: "ANSWER" | "TABLE" | "GRAPH" | "UNSUPPORTED";
  rows?: Array<Record<string, unknown>> | null;
  text: string;
}

export interface AssessmentSummary {
  categorical_value?: string | null;
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dimension: string;
  id: string;
  method_version: string;
  rationale?: string | null;
  score?: number | null;
}

export interface BusinessMapApplicationAssignment {
  application_id: string;
  application_name: string;
  capability_id: string;
}

export interface BusinessMapCapabilityNode {
  description?: string;
  id: string;
  kpis?: Array<string>;
  name: string;
  owner?: string | null;
  tags?: Array<string>;
}

export interface BusinessMapCreateRequest {
  map_key: string;
  state: BusinessMapStateModel;
}

export interface BusinessMapDetail {
  contract_version?: "1.0.0";
  created_at: string;
  id: string;
  map_key: string;
  state: BusinessMapStateModel;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  updated_at: string;
  version: number;
}

export interface BusinessMapFunctionAssignment {
  function_id: string;
  unit_id: string;
}

export interface BusinessMapFunctionNode {
  color?: string;
  description?: string;
  gradient?: string;
  icon?: string;
  id: string;
  name: string;
  processes?: Array<BusinessMapProcessNode>;
}

export interface BusinessMapLane {
  color?: string;
  gradient?: string;
  icon?: string;
  id: string;
  label: string;
  order: number;
  sublabel?: string;
}

export interface BusinessMapList {
  as_of: string;
  contract_version?: "1.0.0";
  maps: Array<BusinessMapSummary>;
  page_info: PageInfo;
}

export interface BusinessMapPlacement {
  capability_id: string;
  maturity: 1 | 2 | 3 | 4 | 5;
  source_function_id?: string | null;
  stage_id?: string | null;
}

export interface BusinessMapProcessNode {
  capabilities?: Array<BusinessMapCapabilityNode>;
  description?: string;
  id: string;
  name: string;
}

export interface BusinessMapRevisionList {
  business_map_id: string;
  contract_version?: "1.0.0";
  revisions: Array<BusinessMapRevisionSummary>;
}

export interface BusinessMapRevisionSummary {
  actor_key: string;
  created_at: string;
  version: number;
}

export interface BusinessMapSaveRequest {
  expected_version: number;
  state: BusinessMapStateModel;
}

export interface BusinessMapSharedGroup {
  capability_ids?: Array<string>;
  description?: string;
  end_stage_id: string;
  id: string;
  name: string;
  start_stage_id: string;
}

export interface BusinessMapStateModel {
  application_assignments?: Array<BusinessMapApplicationAssignment>;
  catalog?: Array<BusinessMapFunctionNode>;
  function_assignments?: Array<BusinessMapFunctionAssignment>;
  organization_units?: Array<BusinessMapLane>;
  placements?: Array<BusinessMapPlacement>;
  shared_groups?: Array<BusinessMapSharedGroup>;
  stages?: Array<BusinessMapLane>;
  template_id: string;
  title: string;
  view_mode?: "value-chain" | "organization";
}

export interface BusinessMapSummary {
  created_at: string;
  id: string;
  map_key: string;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  template_id: string;
  title: string;
  updated_at: string;
  version: number;
  view_mode: "value-chain" | "organization";
}

export interface CalibrationCorpusPublishRequest {
  case_fingerprints: Array<string>;
  corpus_key?: string;
  maximum_affected_scope_mae?: number;
  minimum_candidate_precision?: number;
  minimum_effort_accuracy?: number;
  minimum_recommendation_acceptance?: number;
  minimum_reviewed_cases?: number;
  minimum_validation_success?: number;
  version: string;
}

export interface CalibrationCorpusSummary {
  case_count: number;
  corpus_fingerprint: string;
  corpus_key: string;
  evaluated_at: string;
  evaluation_fingerprint: string;
  id: string;
  metrics_source_version: string;
  observed_metrics: CalibrationObservedMetrics;
  promotion_failures: Array<string>;
  promotion_passed: boolean;
  version: string;
}

export interface CalibrationObservedMetrics {
  affected_scope_mae?: number | null;
  candidate_precision?: number | null;
  effort_accuracy?: number | null;
  recommendation_acceptance?: number | null;
  reviewed_cases: number;
  validation_success?: number | null;
}

export interface CapabilityDefinitionModel {
  aliases?: Array<string>;
  description: string;
  key: string;
  name: string;
  parent_key?: string | null;
}

export interface CapabilityFootprintList {
  as_of: string;
  contract_version?: "1.0.0";
  footprints: Array<CapabilityFootprintModel>;
}

export interface CapabilityFootprintModel {
  application_count: number;
  capability: EntitySummary;
  repository_count: number;
  reuse_signal: number;
  technology_count: number;
  technology_counts: Record<string, number>;
  technology_entropy: number;
}

export interface CapabilityInferenceReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface CapabilityInferenceReviewResult {
  capability_inference_id: string;
  contract_version?: "1.0.0";
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface CapabilityInferenceSummary {
  analyzer: Extractor;
  assertion_class: "CURATED" | "INFERRED";
  capability: CapabilityDefinitionModel;
  confidence: number;
  confidence_band: "HIGH" | "MEDIUM" | "LOW";
  counter_evidence_fact_ids: Array<string>;
  created_at: string;
  id: string;
  model_name?: string | null;
  model_provider?: string | null;
  policy_version: string;
  rationale: string;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_revision: string;
  stale: boolean;
  subject: EntitySummary;
  supporting_fact_ids: Array<string>;
  taxonomy_key: string;
  taxonomy_version: string;
  version: number;
}

export interface CapabilityTaxonomyResponse {
  capabilities: Array<CapabilityDefinitionModel>;
  content_hash: string;
  contract_version?: "1.0.0";
  description: string;
  key: string;
  name: string;
  version: string;
}

export interface Citation {
  fact_id: string;
  href?: string | null;
  label: string;
}

export interface CodePolicyTechnologySummary {
  category_key?: string | null;
  classification: "CURATED" | "CATALOG_MATCH" | "UNCLASSIFIED";
  detected_repository_count: number;
  domain_key?: string | null;
  technology: EntitySummary;
}

export interface CodePolicyViolation {
  fact_ids: Array<string>;
  function_key: string;
  function_name: string;
  matched_technology_id: string;
  message: string;
  rule: "PROHIBITED" | "NOT_ALLOWED";
  technology: EntitySummary;
}

export interface Connector {
  created_at: string;
  display_name: string;
  external_account_key?: string;
  id: string;
  last_error?: string | null;
  last_synced_at?: string | null;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  scopes?: Array<string>;
  status: "CONNECTED" | "NEEDS_REAUTH" | "DISABLED" | "REVOKED";
  updated_at: string;
}

export interface ConnectorList {
  connectors: Array<Connector>;
  contract_version?: "1.0.0";
}

export interface ConnectorRegisterRequest {
  credential_reference?: string;
  display_name: string;
  external_account_key?: string;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  scopes?: Array<string>;
}

export interface ConnectorUpdateRequest {
  credential_reference?: string | null;
  display_name?: string | null;
  scopes?: Array<string> | null;
  status?: "CONNECTED" | "NEEDS_REAUTH" | "DISABLED" | "REVOKED" | null;
}

export interface Coverage {
  facts_with_evidence_ratio: number;
  repositories_scanned: number;
  repositories_total: number;
}

export interface DuplicateCapabilityCandidateSummary {
  capability: CapabilityDefinitionModel;
  capability_inference_ids: Array<string>;
  confidence: number;
  dependencies: Array<EntitySummary>;
  id: string;
  limitations: Array<string>;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_revision: string;
  stale: boolean;
  summary: string;
  supporting_fact_ids: Array<string>;
  version: number;
}

export interface DuplicateCapabilityReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface DuplicateCapabilityReviewResult {
  contract_version?: "1.0.0";
  duplicate_capability_candidate_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface EcosystemAdmissionEvaluateRequest {
  minimum_dependency_share?: number;
  minimum_repositories?: number;
}

export interface EcosystemAdmissionSummary {
  calibration_gate_passed: boolean;
  decided_at?: string | null;
  decided_by?: string | null;
  decision_fingerprint: string;
  ecosystem: "PYPI" | "MAVEN" | "CARGO" | "NUGET";
  metadata_parity: boolean;
  minimum_dependency_share: number;
  minimum_repositories: number;
  observed_dependency_share: number;
  observed_repositories: number;
  predecessor_admitted: boolean;
  reasons: Array<string>;
  sequence: number;
  status: "NOT_EVALUATED" | "PROPOSED" | "ADMITTED" | "RETIRED" | "STALE";
}

export interface EntitySummary {
  canonical_key?: string | null;
  id: string;
  kind: string;
  name: string;
  summary?: string | null;
}

export interface EstateCounts {
  applications: number;
  repositories: number;
  services: number;
  technologies: number;
}

export interface EstateSummary {
  as_of: string;
  contract_version?: "1.0.0";
  counts: EstateCounts;
  coverage: Coverage;
  distributions: Record<string, number>;
  page_info?: PageInfo | null;
  ranked_items: Array<RankedItem>;
}

export interface EvidenceDetail {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  closed_at?: string | null;
  confidence: number;
  contract_version?: "1.0.0";
  effective_at?: string | null;
  evidence: Array<Record<string, unknown>>;
  extractor: Extractor;
  fact_id: string;
  observed_at: string;
  predicate: string;
  properties?: Record<string, unknown> | null;
  source_revision: string;
}

export interface Extractor {
  key: string;
  version: string;
}

export interface Freshness {
  effective_at?: string | null;
  observed_at: string;
  source_key?: string | null;
  status: "FRESH" | "STALE" | "UNKNOWN";
}

export interface GitHubInstallationConnectRequest {
  display_name?: string | null;
  installation_id: string;
  pilot_manual_binding_acknowledged: true;
}

export interface GitHubInstallationSetupRequest {
  return_to?: string;
}

export interface GitHubInstallationSetupResponse {
  expires_at: string;
  setup_url: string;
}

export interface GitHubRepositoryConnectRequest {
  credential_reference?: "env://GITHUB_TOKEN";
  repository: string;
}

export interface GitHubRepositoryOption {
  archived?: boolean;
  default_branch?: string | null;
  full_name: string;
  visibility: "public" | "private" | "internal";
}

export interface GitHubRepositoryOptionList {
  contract_version?: "1.0.0";
  repositories: Array<GitHubRepositoryOption>;
  token_configured: boolean;
  truncated?: boolean;
}

export interface GraphEdge {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  citation_fact_ids: Array<string>;
  confidence: number;
  id: string;
  predicate: string;
  review_state: "CONFIRMED" | "POSSIBLE" | "REJECTED" | "NOT_APPLICABLE";
  source: string;
  target: string;
}

export interface GraphNeighborhood {
  center_id: string;
  contract_version?: "1.0.0";
  edges: Array<GraphEdge>;
  highlighted_path?: Array<string> | null;
  nodes: Array<GraphNode>;
  truncated: boolean;
  truncation_reason?: string | null;
}

export interface GraphNode {
  aggregate: boolean;
  confidence?: number | null;
  id: string;
  key: string;
  label: string;
  member_count?: number | null;
  namespace: "BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "INTELLIGENCE";
  type: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface IdentityReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface IdentityReviewResult {
  contract_version?: "1.0.0";
  identity_assertion_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface InternalCatalogComponentSummary {
  catalog_fingerprint: string;
  component_key: string;
  governed_at?: string | null;
  governed_by?: string | null;
  id: string;
  name: string;
  owner?: string | null;
  review_state: "UNREVIEWED" | "APPROVED" | "REJECTED";
  status: "APPROVED" | "DEPRECATED" | "BLOCKED";
  supporting_fact_ids: Array<string>;
  version: string;
}

export interface InternalCatalogComponentUpsertRequest {
  api_symbols?: Array<string>;
  behavior_claims?: Array<Record<string, unknown>>;
  capability_definition_id: string;
  component_entity_id: string;
  decision: "APPROVE" | "REJECT";
  license?: string | null;
  owner: string;
  policy_tags?: Array<string>;
  runtime_constraints?: Record<string, string>;
  security_status?: "CLEAR" | "WARN" | "BLOCKED" | "UNKNOWN";
  status?: "APPROVED" | "DEPRECATED" | "BLOCKED";
  supporting_fact_ids: Array<string>;
  version: string;
}

export interface InternalUsage {
  application_count: number;
  repositories?: Array<EntitySummary> | null;
  repository_count: number;
}

export interface MemberInviteRequest {
  actor_key: string;
  display_name?: string;
  email?: string;
  role?: "view" | "review" | "execute" | "admin";
}

export interface MemberUpdateRequest {
  role?: "view" | "review" | "execute" | "admin" | null;
  status?: "INVITED" | "ACTIVE" | "SUSPENDED" | null;
}

export interface ModernizationCandidateModel {
  analyzer: Extractor;
  capability?: CapabilityDefinitionModel | null;
  confidence: number;
  counter_evidence_fact_ids: Array<string>;
  id: string;
  impact?: ModernizationImpactModel | null;
  kind: "DEPENDENCY_CONSOLIDATION" | "INTERNAL_DUPLICATION" | "VENDORED_DUPLICATION" | "NATIVE_REPLACEMENT";
  options: Array<ModernizationOptionModel>;
  recommendation?: ModernizationRecommendationModel | null;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_locations: Array<Record<string, unknown>>;
  source_revision: string;
  stale: boolean;
  subjects: Array<EntitySummary>;
  summary: string;
  supporting_fact_ids: Array<string>;
  validation_gaps: Array<string>;
  version: number;
}

export interface ModernizationCandidateReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface ModernizationCandidateReviewResult {
  contract_version?: "1.0.0";
  modernization_candidate_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface ModernizationGovernanceState {
  active_calibration?: CalibrationCorpusSummary | null;
  active_policy?: ModernizationPolicySummary | null;
  contract_version?: "1.0.0";
  ecosystem_admissions: Array<EcosystemAdmissionSummary>;
  internal_components: Array<InternalCatalogComponentSummary>;
}

export interface ModernizationImpactModel {
  affected_call_sites: number;
  affected_files: number;
  affected_test_files: Array<string>;
  build_touchpoints: Array<Record<string, unknown>>;
  confidence: number;
  configuration_touchpoints: Array<Record<string, unknown>>;
  covered_call_sites: number;
  deployment_touchpoints: Array<Record<string, unknown>>;
  dynamic_signals: Array<string>;
  effort_model_version: string;
  effort_points: number;
  evidence_locations: Array<Record<string, unknown>>;
  limitations: Array<string>;
  uncovered_call_sites: number;
}

export interface ModernizationList {
  as_of: string;
  contract_version?: "1.0.0";
  opportunities: Array<RankedItem>;
  page_info: PageInfo;
}

export interface ModernizationOptionEligibilityModel {
  api_fit: "PASS" | "FAIL" | "UNKNOWN";
  behavior_fit: "PASS" | "FAIL" | "UNKNOWN";
  capability_fit: "PASS" | "FAIL" | "UNKNOWN";
  disqualifiers: Array<string>;
  eligible: boolean;
  evidence: Record<string, unknown>;
  license_fit: "PASS" | "FAIL" | "UNKNOWN";
  policy_fit: "PASS" | "FAIL" | "UNKNOWN";
  runtime_fit: "PASS" | "FAIL" | "UNKNOWN";
  security_fit: "PASS" | "FAIL" | "UNKNOWN";
  unknowns: Array<string>;
}

export interface ModernizationOptionModel {
  canonical_key: string;
  compatibility: "OBSERVED" | "COMPATIBLE" | "UNKNOWN" | "INCOMPATIBLE";
  disqualifiers: Array<string>;
  eligibility?: ModernizationOptionEligibilityModel | null;
  id: string;
  kind: "NATIVE" | "INTERNAL" | "UPGRADE" | "PACKAGE";
  name: string;
  rank: number;
  rationale: string;
  score: number;
  score_components: Record<string, number>;
  supporting_fact_ids: Array<string>;
  target_entity?: EntitySummary | null;
  tradeoffs: Array<string>;
  validation_gaps: Array<string>;
}

export interface ModernizationPolicyPublishRequest {
  allowed_licenses?: Array<string>;
  allowed_security_statuses?: Array<"CLEAR" | "WARN" | "BLOCKED" | "UNKNOWN">;
  denied_option_keys?: Array<string>;
  policy_key?: string;
  required_policy_tags?: Array<string>;
  runtime_versions?: Record<string, string>;
  version: string;
}

export interface ModernizationPolicySummary {
  activated_at: string;
  activated_by: string;
  allowed_licenses: Array<string>;
  allowed_security_statuses: Array<string>;
  configuration_fingerprint: string;
  denied_option_keys: Array<string>;
  id: string;
  policy_key: string;
  required_policy_tags: Array<string>;
  runtime_versions: Record<string, string>;
  status: "DRAFT" | "ACTIVE" | "RETIRED";
  version: string;
}

export interface ModernizationRecommendationModel {
  action: "CONSOLIDATE" | "REPLACE" | "UPGRADE" | "REFACTOR" | "INVESTIGATE";
  affected_call_sites: number;
  affected_files: number;
  confidence: number;
  counter_evidence_fact_ids: Array<string>;
  counter_signals: Array<string>;
  created_at: string;
  estimated_effort: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  id: string;
  migration_plan: Array<string>;
  objective: string;
  policy_version: string;
  rationale: string;
  review_state: "UNREVIEWED" | "ACCEPTED" | "REJECTED" | "DISMISSED";
  rollback_plan: Array<string>;
  selected_option_id?: string | null;
  stale: boolean;
  supporting_fact_ids: Array<string>;
  title: string;
  validation_gaps: Array<string>;
  version: number;
}

export interface ModernizationRecommendationReviewRequest {
  decision: "ACCEPT" | "REJECT" | "DISMISS";
  expected_version: number;
  rationale: string;
}

export interface ModernizationRecommendationReviewResult {
  contract_version?: "1.0.0";
  modernization_recommendation_id: string;
  review_state: "ACCEPTED" | "REJECTED" | "DISMISSED";
  reviewed_at: string;
  version: number;
}

export interface ModernizationScenarioItem {
  action: "CONSOLIDATE" | "REPLACE" | "UPGRADE" | "REFACTOR" | "INVESTIGATE";
  effort_points: number;
  policy_version: string;
  recommendation_id: string;
  repository: EntitySummary;
  score: number;
  score_components: Record<string, number>;
  selected: boolean;
  title: string;
}

export interface ModernizationScenarioRequest {
  budget_points: number;
  excluded_recommendation_ids?: Array<string>;
}

export interface ModernizationScenarioResult {
  as_of: string;
  budget_points: number;
  contract_version?: "1.0.0";
  items: Array<ModernizationScenarioItem>;
  total_score: number;
  used_points: number;
}

export interface ModernizationValidationOutcomeRequest {
  actual_call_sites?: number | null;
  actual_effort?: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN" | null;
  actual_files?: number | null;
  failed_checks?: Array<string>;
  notes: string;
  successful_checks?: Array<string>;
  validation_status: "SUCCEEDED" | "PARTIAL" | "FAILED";
}

export interface ModernizationValidationOutcomeResult {
  contract_version?: "1.0.0";
  id: string;
  modernization_recommendation_id: string;
  reported_at: string;
  validation_status: "SUCCEEDED" | "PARTIAL" | "FAILED";
}

export interface PackageSource {
  freshness: Freshness;
  origin: string;
  registry_key: string;
  tenant_scoped: boolean;
  visibility: "PUBLIC" | "PRIVATE" | "UNKNOWN";
}

export interface PageInfo {
  has_next_page: boolean;
  next_cursor?: string | null;
}

export interface Phase3IntelligenceMetrics {
  affected_call_site_mae?: number | null;
  affected_files_mae?: number | null;
  as_of: string;
  candidate_counts: Record<string, number>;
  candidate_review_precision?: number | null;
  contract_version?: "1.0.0";
  dead_letter_count: number;
  effort_band_accuracy?: number | null;
  evidence_completeness_rate?: number | null;
  job_counts: Record<string, number>;
  job_latency_ms_p50?: number | null;
  job_latency_ms_p95?: number | null;
  model_cost_usd: number;
  model_invocation_count: number;
  model_latency_ms_p95?: number | null;
  queue_lag_seconds_p50?: number | null;
  queue_lag_seconds_p95?: number | null;
  recommendation_acceptance_rate?: number | null;
  recommendation_counts: Record<string, number>;
  retry_count: number;
  stale_candidate_count: number;
  stale_recommendation_count: number;
  successful_validation_rate?: number | null;
}

export interface ProviderQuota {
  backoff_until?: string | null;
  limit?: number | null;
  observed_at: string;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  resets_at?: string | null;
  status: "OK" | "THROTTLED" | "EXHAUSTED";
  used: number;
}

export interface RankedItem {
  citations?: Array<Citation> | null;
  domain: "BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "INTELLIGENCE";
  freshness: Freshness;
  id: string;
  kind: string;
  name: string;
  priority: Score;
  summary?: string | null;
  viability?: Score | null;
}

export interface RecommendationSummary {
  action: "RETAIN" | "UPGRADE" | "REMOVE" | "REPLACE" | "CONSOLIDATE" | "REFACTOR" | "REBUILD" | "REPLATFORM" | "RETIRE" | "INVESTIGATE";
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  counter_signals?: Array<string> | null;
  estimated_effort?: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN" | null;
  id: string;
  rationale: string;
  status: "PROPOSED" | "ACCEPTED" | "REJECTED" | "PLANNED" | "IN_PROGRESS" | "COMPLETED" | "DISMISSED";
  target?: EntitySummary | null;
  title: string;
}

export interface RepositoryCapabilityIntelligence {
  contract_version?: "1.0.0";
  duplicate_candidates: Array<DuplicateCapabilityCandidateSummary>;
  inferences: Array<CapabilityInferenceSummary>;
  repository: EntitySummary;
  taxonomy_key?: string | null;
  taxonomy_version?: string | null;
}

export interface RepositoryCodePolicyEvaluation {
  evaluated_at: string;
  evaluated_by: string;
  evidence_fingerprint: string;
  id: string;
  policy_set_fingerprint: string;
  repository: EntitySummary;
  status: "COMPLIANT" | "MISALIGNED" | "UNASSESSED" | "STALE";
  unclassified_technologies: Array<EntitySummary>;
  violations: Array<CodePolicyViolation>;
}

export interface RepositoryDetail {
  applications: Array<EntitySummary>;
  contract_version?: "1.0.0";
  deployments: Array<EntitySummary>;
  freshness: Freshness;
  profile?: RepositoryProfile | null;
  repository: EntitySummary;
  technologies: Array<EntitySummary>;
}

export interface RepositoryModernizationIntelligence {
  candidates: Array<ModernizationCandidateModel>;
  contract_version?: "1.0.0";
  repository: EntitySummary;
  source_revision?: string | null;
  truncated: boolean;
}

export interface RepositoryProfile {
  citations: Array<Citation>;
  components?: Array<string>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  descriptions?: Array<string>;
  key_files?: Array<string>;
  languages?: Array<string>;
  limitations?: Array<string>;
  operational_signals?: Array<string>;
  purpose?: string | null;
  purpose_source?: string | null;
  source_revision: string;
}

export interface RescanJob {
  completed_at?: string | null;
  connector_id?: string | null;
  created_at: string;
  id: string;
  last_error?: string | null;
  reason?: string;
  requested_by: string;
  started_at?: string | null;
  status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
}

export interface RescanJobList {
  contract_version?: "1.0.0";
  jobs: Array<RescanJob>;
  page_info: PageInfo;
}

export interface RescanRequest {
  connector_id?: string | null;
  idempotency_key: string;
  reason?: string;
}

export interface ReviewQueue {
  as_of: string;
  contract_version?: "1.0.0";
  counts: Record<string, number>;
  items: Array<ReviewQueueItem>;
  page_info: PageInfo;
}

export interface ReviewQueueItem {
  confidence: number;
  confidence_band: "HIGH" | "MEDIUM" | "LOW";
  created_at: string;
  item_id: string;
  item_type: "IDENTITY_ASSERTION" | "CAPABILITY_INFERENCE" | "DUPLICATE_CAPABILITY" | "MODERNIZATION_CANDIDATE" | "MODERNIZATION_RECOMMENDATION";
  repository_id?: string | null;
  review_path: string;
  review_state: string;
  summary?: string | null;
  title: string;
  version: number;
}

export interface ScanPolicy {
  cadence: "HOURLY" | "DAILY" | "WEEKLY" | "MANUAL";
  contract_version?: "1.0.0";
  enabled: boolean;
  updated_at?: string | null;
  updated_by?: string | null;
}

export interface ScanPolicyUpdateRequest {
  cadence: "HOURLY" | "DAILY" | "WEEKLY" | "MANUAL";
  enabled?: boolean;
}

export interface ScanStatus {
  as_of: string;
  contract_version?: "1.0.0";
  policy: ScanPolicy;
  quotas: Array<ProviderQuota>;
  recent_jobs: Array<RescanJob>;
}

export interface Score {
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  method_version: string;
  value: number;
}

export interface ServiceControlRequest {
  desired_state: "RUNNING" | "STOPPED";
}

export interface ServiceStatus {
  category: "CORE" | "INGESTION" | "ENRICHMENT" | "GRAPH" | "INTELLIGENCE";
  configured?: boolean;
  controllable?: boolean;
  desired_state?: "RUNNING" | "STOPPED";
  detail?: string;
  failed?: number;
  key: string;
  last_activity_at?: string | null;
  last_heartbeat_at?: string | null;
  management_scope?: string;
  name: string;
  pending?: number;
  running?: number;
  state: "RUNNING" | "IDLE" | "WAITING" | "DEGRADED" | "OFFLINE" | "STOPPING" | "STOPPED";
}

export interface ServiceStatusList {
  as_of: string;
  contract_version?: "1.0.0";
  services: Array<ServiceStatus>;
}

export interface SessionInfo {
  actor_key: string;
  capabilities: Array<string>;
  contract_version?: "1.0.0";
  tenant_id?: string | null;
}

export interface TaxonomySummary {
  key: string;
  name: string;
  summary?: string | null;
}

export interface TechnologyCatalogProfile {
  catalog_technology?: EntitySummary | null;
  category?: TaxonomySummary | null;
  citations: Array<Citation>;
  classification: "CURATED" | "CATALOG_MATCH" | "UNCLASSIFIED";
  dependents?: number | null;
  domain?: TaxonomySummary | null;
  ecosystem?: string | null;
  functions?: Array<TaxonomySummary>;
  homepage?: string | null;
  installation_command?: string | null;
  latest_version?: string | null;
  license?: string | null;
  package_name?: string | null;
  package_url?: string | null;
  repository_url?: string | null;
  summary?: string | null;
  versions?: number | null;
  weekly_downloads?: number | null;
}

export interface TechnologyDetail {
  alternatives?: Array<EntitySummary> | null;
  assessments: Array<AssessmentSummary>;
  catalog_profile?: TechnologyCatalogProfile | null;
  contract_version?: "1.0.0";
  freshness: Freshness;
  internal_usage: InternalUsage;
  migration_patterns?: Array<EntitySummary> | null;
  packages: Array<EntitySummary>;
  projects: Array<EntitySummary>;
  recommendations: Array<RecommendationSummary>;
  registry_sources?: Array<PackageSource> | null;
  technology: EntitySummary;
}

export interface TechnologyEstateHierarchy {
  as_of: string;
  contract_version?: "1.0.0";
  nodes: Array<TechnologyEstateHierarchyNode>;
  truncated?: boolean;
}

export interface TechnologyEstateHierarchyNode {
  catalog_profile?: TechnologyCatalogProfile | null;
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dependent_applications: Array<EntitySummary>;
  depth: number;
  direct: boolean;
  parent_technology_id?: string | null;
  relationship: string;
  technology: EntitySummary;
}

export interface TenantCodeFunctionPolicySummary {
  allowed_technology_ids: Array<string>;
  id: string;
  policy_fingerprint: string;
  prohibited_technology_ids: Array<string>;
  updated_at: string;
  updated_by: string;
}

export interface TenantCodeFunctionSummary {
  description: string;
  domain_key: string;
  function_key: string;
  name: string;
  policy?: TenantCodeFunctionPolicySummary | null;
  source: "PRIMARY" | "CUSTOM";
  status: "ACTIVE" | "RETIRED";
}

export interface TenantCodeFunctionUpsertRequest {
  allowed_technology_ids?: Array<string>;
  description?: string;
  domain_key: string;
  name: string;
  prohibited_technology_ids?: Array<string>;
  source: "PRIMARY" | "CUSTOM";
  status?: "ACTIVE" | "RETIRED";
}

export interface TenantCodePolicyState {
  available_technologies: Array<CodePolicyTechnologySummary>;
  contract_version?: "1.0.0";
  evaluations: Array<RepositoryCodePolicyEvaluation>;
  functions: Array<TenantCodeFunctionSummary>;
  policy_set_fingerprint: string;
  summary: TenantCodePolicySummary;
  technology_catalog_truncated?: boolean;
}

export interface TenantCodePolicySummary {
  compliant_repositories: number;
  custom_functions: number;
  evaluated_repositories: number;
  governed_functions: number;
  misaligned_repositories: number;
  stale_repositories: number;
}

export interface TenantMember {
  actor_key: string;
  created_at: string;
  display_name?: string;
  email?: string;
  id: string;
  role: "view" | "review" | "execute" | "admin";
  status: "INVITED" | "ACTIVE" | "SUSPENDED";
  updated_at: string;
}

export interface TenantMemberList {
  contract_version?: "1.0.0";
  members: Array<TenantMember>;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}
