// Generated by scripts/generate_contract_types.mjs from the canonical OpenAPI document.
// Do not edit by hand. Run `pnpm contracts:generate`.

export interface ActionSubject {
  dependent_count?: number;
  entity: EntitySummary;
  evidence_fact_ids?: Array<string>;
  observed_versions?: Array<string>;
  resolution?: "RESOLVED";
}

export interface ActionSubjectCapability {
  enabled: boolean;
  lifecycle: "ACTIVE" | "DISABLED" | "RETIRED";
  subject_type: string;
}

export interface ActionSubjectList {
  contract_version?: "1.0.0";
  page_info: PageInfo;
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  subjects: Array<ActionSubject>;
}

export interface ActionTypeList {
  action_types: Array<ActionTypeSummary>;
  contract_version?: "1.0.0";
  policy_version: string;
}

export interface ActionTypeSummary {
  description: string;
  enabled: boolean;
  label: string;
  lifecycle: "ACTIVE" | "DISABLED" | "RETIRED";
  ontology_version: string;
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  subject_types: Array<string>;
  subjects?: Array<ActionSubjectCapability>;
}

export interface AgentApprovalDecisionRequest {
  decision: "APPROVED" | "REJECTED";
  expected_version: number;
  rationale: string;
}

export interface AgentApprovalModel {
  created_at: string;
  decided_at?: string | null;
  decided_by?: string | null;
  envelope_id: string;
  expires_at: string;
  id: string;
  operation_key: string;
  rationale?: string | null;
  reason_code: string;
  requested_by: string;
  status: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED";
  version: number;
}

export interface AgentAuthorizationDecisionModel {
  approval_id?: string | null;
  decided_at: string;
  decision: "ALLOW" | "CONSTRAIN" | "ESCALATE" | "DENY";
  envelope_id: string;
  id: string;
  operation_key: string;
  reason_codes: Array<string>;
  request_fingerprint: string;
}

export interface AgentAuthorizeRequest {
  operation_key: string;
  request_payload?: Record<string, unknown>;
}

export interface AgentControlDrillRequest {
  drill_kind: "KILL_SWITCH" | "ROLLBACK" | "AUDIT_RECONSTRUCTION";
  envelope_id?: string | null;
  flight_record_id?: string | null;
}

export interface AgentControlDrillResult {
  checks: Array<Record<string, unknown>>;
  drill_kind: "KILL_SWITCH" | "ROLLBACK" | "AUDIT_RECONSTRUCTION";
  id: string;
  performed_at: string;
  performed_by: string;
  status: "PASSED" | "FAILED";
}

export interface AgentKillSwitchModel {
  contract_version?: "1.0.0";
  engaged: boolean;
  reason: string;
  updated_at: string;
  updated_by: string;
  version: number;
}

export interface AgentKillSwitchUpdateRequest {
  engaged: boolean;
  expected_version: number;
  reason: string;
}

export interface AgentOperationRequest {
  constraints?: Record<string, unknown>;
  destructive?: boolean;
  operation_key: string;
  requested_band: "READ" | "EXECUTE" | "CONDITIONAL" | "PROHIBITED" | "ESCALATE";
}

export interface AIProviderConfiguration {
  contract_version?: "1.0.0";
  enabled?: boolean;
  enrichment_status?: "DISABLED" | "READY" | "QUEUED" | "RUNNING" | "ACTIVE" | "DEGRADED";
  failed_enrichment_jobs?: number;
  key_configured?: boolean;
  key_fingerprint?: string | null;
  last_enrichment_at?: string | null;
  last_error?: string | null;
  model?: string;
  pending_enrichment_jobs?: number;
  provider: "openrouter" | "openai" | "anthropic";
  running_enrichment_jobs?: number;
  test_status?: "NOT_TESTED" | "SUCCEEDED" | "FAILED";
  tested_at?: string | null;
  updated_at?: string | null;
  updated_by?: string | null;
}

export interface AIProviderConfigurationUpdateRequest {
  api_key?: string | null;
  enabled?: boolean;
  model?: string;
  provider: "openrouter" | "openai" | "anthropic";
}

export interface AIProviderConnectionTest {
  contract_version?: "1.0.0";
  models?: Array<string>;
  provider: "openrouter" | "openai" | "anthropic";
  status?: "SUCCEEDED";
}

export interface AISupplyChain {
  as_of: string;
  contract_version?: "1.0.0";
  coverage_ratio?: number | null;
  entities?: Array<EntitySummary>;
  limitations?: Array<GateReason>;
  links?: Array<AISupplyChainLink>;
  status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
}

export interface AISupplyChainLink {
  confidence: number;
  evidence_fact_ids: Array<string>;
  object: EntitySummary;
  predicate: string;
  subject: EntitySummary;
}

export interface ApplicationComponentDependencyHierarchy {
  component_path: string;
  dependencies: Array<ApplicationDependencyNode>;
  truncated?: boolean;
}

export interface ApplicationDependencyNode {
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dependency_relation?: string | null;
  depth: number;
  direct: boolean;
  parent_technology_id?: string | null;
  relationship: string;
  requirement?: string | null;
  scope?: string | null;
  technology: EntitySummary;
}

export interface ApplicationDetail {
  application: EntitySummary;
  assessments: Array<AssessmentSummary>;
  business_context: Array<EntitySummary>;
  contract_version?: "1.0.0";
  dependency_hierarchies?: Array<ApplicationRepositoryDependencyHierarchy>;
  deployments: Array<EntitySummary>;
  freshness: Freshness;
  graph_intelligence?: EntityGraphIntelligence | null;
  recommendations: Array<RecommendationSummary>;
  repositories: Array<EntitySummary>;
  services: Array<EntitySummary>;
  technologies: Array<EntitySummary>;
  technology_groups: Array<ApplicationTechnologyGroup>;
}

export interface ApplicationRepositoryDependencyHierarchy {
  components: Array<ApplicationComponentDependencyHierarchy>;
  repository: EntitySummary;
}

export interface ApplicationSimilarityCandidate {
  application: EntitySummary;
  components: Record<string, unknown>;
  coverage: Record<string, unknown>;
  created_at: string;
  differences: Record<string, unknown>;
  id: string;
  limitations?: Array<Record<string, unknown>>;
  method_version: string;
  overlaps: Record<string, unknown>;
  review_state: "UNREVIEWED" | "CONFIRMED_SIMILAR" | "CONFIRMED_DISTINCT" | "CONSOLIDATION_CANDIDATE" | "DISMISSED";
  score: number;
}

export interface ApplicationSimilarityList {
  as_of: string;
  candidates?: Array<ApplicationSimilarityCandidate>;
  contract_version?: "1.0.0";
  limitations?: Array<Record<string, unknown>>;
  page_info?: PageInfo | null;
  subject: EntitySummary;
}

export interface ApplicationSimilarityReviewRequest {
  decision: "CONFIRMED_SIMILAR" | "CONFIRMED_DISTINCT" | "CONSOLIDATION_CANDIDATE" | "DISMISSED" | "REOPENED";
  rationale?: string;
  reason_code: string;
}

export interface ApplicationSimilarityReviewResult {
  candidate_id: string;
  contract_version?: "1.0.0";
  review_state: "UNREVIEWED" | "CONFIRMED_SIMILAR" | "CONFIRMED_DISTINCT" | "CONSOLIDATION_CANDIDATE" | "DISMISSED";
  reviewed_at: string;
}

export interface ApplicationTechnologyFunction {
  function: TaxonomySummary;
  technologies: Array<ApplicationTechnologyUsage>;
}

export interface ApplicationTechnologyGroup {
  domain: TaxonomySummary;
  functions: Array<ApplicationTechnologyFunction>;
}

export interface ApplicationTechnologyResourceDetails {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  config_keys?: Array<string>;
  engine: string;
  inference_method?: string | null;
  limitations?: Array<string>;
  package_dependencies?: Array<string>;
  providers?: Array<string>;
  resource_kind: "DATABASE" | "CACHE" | "OBJECT_STORAGE";
  signal_kinds?: Array<string>;
  source_referenced?: boolean;
}

export interface ApplicationTechnologyUsage {
  category?: TaxonomySummary | null;
  citations: Array<Citation>;
  classification: "CURATED" | "CATALOG_MATCH" | "DETERMINISTIC" | "UNCLASSIFIED";
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  resource_details?: ApplicationTechnologyResourceDetails | null;
  technology: EntitySummary;
}

export interface ArchitectureAspectModel {
  definition: string;
  key: string;
  label: string;
}

export interface ArchitectureCapabilityModel {
  aliases?: Array<string>;
  concern_key: string;
  definition: string;
  key: string;
  name: string;
}

export interface ArchitectureCellDefinitionModel {
  absence_assertable?: boolean;
  aspect_keys?: Array<string>;
  bindings: Array<CanvasBindingModel>;
  concern_key: string;
  default_expectation: CellExpectationModel;
  definition: string;
  key: string;
  label: string;
  observation_rule_key: string;
  required_sensor_kinds: Array<string>;
}

export interface ArchitectureConcernModel {
  definition: string;
  domain_key: "experience" | "application" | "integration" | "data" | "platform" | "delivery";
  key: string;
  label: string;
  order: number;
}

export interface ArchitectureDomainModel {
  definition: string;
  key: "experience" | "application" | "integration" | "data" | "platform" | "delivery";
  label: string;
  order: number;
  question: string;
}

export interface ArchitectureProfileCreateRequest {
  profile_key: string;
  state: ArchitectureProfileStateModel;
}

export interface ArchitectureProfileDetail {
  created_at: string;
  fingerprint: string;
  id: string;
  name: string;
  profile_key: string;
  reference_model_key: string;
  reference_model_version: string;
  state: ArchitectureProfileStateModel;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  updated_at: string;
  version: number;
}

export interface ArchitectureProfileList {
  contract_version?: "1.0.0";
  profiles: Array<ArchitectureProfileSummary>;
}

export interface ArchitectureProfilePublishRequest {
  expected_version: number;
}

export interface ArchitectureProfileStateModel {
  cell_policies?: Array<TenantCellPolicyModel>;
  extension_cells?: Array<TenantExtensionCellModel>;
  name: string;
  reference_model_key: string;
  reference_model_version: string;
}

export interface ArchitectureProfileSummary {
  created_at: string;
  fingerprint: string;
  id: string;
  name: string;
  profile_key: string;
  reference_model_key: string;
  reference_model_version: string;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  updated_at: string;
  version: number;
}

export interface ArchitectureProfileUpdateRequest {
  expected_version: number;
  state: ArchitectureProfileStateModel;
}

export interface ArchitectureReferenceModel {
  cells: Array<ArchitectureCellDefinitionModel>;
  content_hash: string;
  contract_version?: "1.0.0";
  description: string;
  key: string;
  name: string;
  taxonomy_content_hash: string;
  taxonomy_key: string;
  taxonomy_version: string;
  version: string;
}

export interface ArchitectureReferenceModelList {
  contract_version?: "1.0.0";
  models: Array<ArchitectureReferenceModel>;
}

export interface ArchitectureTaxonomyResponse {
  aspects: Array<ArchitectureAspectModel>;
  capabilities: Array<ArchitectureCapabilityModel>;
  concerns: Array<ArchitectureConcernModel>;
  content_hash: string;
  contract_version?: "1.0.0";
  description: string;
  domains: Array<ArchitectureDomainModel>;
  key: string;
  name: string;
  version: string;
}

export interface AskRequest {
  context_entity_ids?: Array<string> | null;
  question: string;
}

export interface AskResponse {
  citations: Array<Citation>;
  contract_version?: "1.0.0";
  graph_highlight?: GraphNeighborhood | null;
  resolved_entities?: Array<ResolvedEntity>;
  result_kind: "ANSWER" | "TABLE" | "GRAPH" | "UNSUPPORTED";
  rows?: Array<Record<string, unknown>> | null;
  text: string;
}

export interface AssessmentSummary {
  categorical_value?: string | null;
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dimension: string;
  id: string;
  method_version: string;
  rationale?: string | null;
  score?: number | null;
}

export interface AssumptionClaimCreateRequest {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  claim_key: string;
  confidence: number;
  display_value: string;
  observed_at: string;
  opposing_fact_ids?: Array<string>;
  source_key: string;
  supporting_fact_ids?: Array<string>;
}

export interface AssumptionClaimModel {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  claim_key: string;
  confidence: number;
  display_value: string;
  id: string;
  observed_at: string;
  opposing_fact_ids?: Array<string>;
  source_key: string;
  supporting_fact_ids?: Array<string>;
}

export interface AssumptionCreateRequest {
  authority: string;
  claims?: Array<AssumptionClaimCreateRequest>;
  confidence: number;
  dependent_entity_ids?: Array<string>;
  dimension: string;
  last_verified_at: string;
  statement: string;
  subject_entity_id: string;
}

export interface AssumptionList {
  assumptions: Array<AssumptionModel>;
  contract_version?: "1.0.0";
  page_info: PageInfo;
}

export interface AssumptionModel {
  authority: string;
  claims?: Array<AssumptionClaimModel>;
  confidence: number;
  contradiction_ids?: Array<string>;
  created_at: string;
  dependent_entity_ids?: Array<string>;
  dimension: string;
  id: string;
  last_verified_at: string;
  statement: string;
  status: "OPEN" | "ACCEPTED" | "REJECTED" | "SUPERSEDED";
  subject: EntitySummary;
  updated_at: string;
  version: number;
}

export interface BusinessMapApplicationAssignment {
  application_id: string;
  application_name: string;
  capability_id: string;
}

export interface BusinessMapCapabilityNode {
  criticality?: 1 | 2 | 3 | 4 | 5;
  description?: string;
  id: string;
  kpis?: Array<string>;
  name: string;
  owner?: string | null;
  tags?: Array<string>;
}

export interface BusinessMapCreateRequest {
  map_key: string;
  state: BusinessMapStateModel;
}

export interface BusinessMapDetail {
  contract_version?: "1.0.0";
  created_at: string;
  id: string;
  map_key: string;
  state: BusinessMapStateModel;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  updated_at: string;
  version: number;
}

export interface BusinessMapFunctionAssignment {
  function_id: string;
  unit_id: string;
}

export interface BusinessMapFunctionNode {
  color?: string;
  description?: string;
  gradient?: string;
  icon?: string;
  id: string;
  name: string;
  processes?: Array<BusinessMapProcessNode>;
}

export interface BusinessMapLane {
  color?: string;
  gradient?: string;
  icon?: string;
  id: string;
  label: string;
  order: number;
  sublabel?: string;
}

export interface BusinessMapList {
  as_of: string;
  contract_version?: "1.0.0";
  maps: Array<BusinessMapSummary>;
  page_info: PageInfo;
}

export interface BusinessMapPlacement {
  capability_id: string;
  maturity: 1 | 2 | 3 | 4 | 5;
  source_function_id?: string | null;
  stage_id?: string | null;
}

export interface BusinessMapProcessNode {
  capabilities?: Array<BusinessMapCapabilityNode>;
  description?: string;
  id: string;
  name: string;
}

export interface BusinessMapRevisionList {
  business_map_id: string;
  contract_version?: "1.0.0";
  revisions: Array<BusinessMapRevisionSummary>;
}

export interface BusinessMapRevisionSummary {
  actor_key: string;
  created_at: string;
  version: number;
}

export interface BusinessMapSaveRequest {
  expected_version: number;
  state: BusinessMapStateModel;
}

export interface BusinessMapSharedGroup {
  capability_ids?: Array<string>;
  description?: string;
  end_stage_id: string;
  id: string;
  name: string;
  start_stage_id: string;
}

export interface BusinessMapStateModel {
  application_assignments?: Array<BusinessMapApplicationAssignment>;
  catalog?: Array<BusinessMapFunctionNode>;
  function_assignments?: Array<BusinessMapFunctionAssignment>;
  organization_units?: Array<BusinessMapLane>;
  placements?: Array<BusinessMapPlacement>;
  shared_groups?: Array<BusinessMapSharedGroup>;
  stages?: Array<BusinessMapLane>;
  template_id: string;
  title: string;
  view_mode?: "value-chain" | "organization";
}

export interface BusinessMapSummary {
  created_at: string;
  id: string;
  map_key: string;
  status: "DRAFT" | "ACTIVE" | "ARCHIVED";
  template_id: string;
  title: string;
  updated_at: string;
  version: number;
  view_mode: "value-chain" | "organization";
}

export interface CalibrationCorpusPublishRequest {
  case_fingerprints: Array<string>;
  corpus_key?: string;
  maximum_affected_scope_mae?: number;
  minimum_candidate_precision?: number;
  minimum_effort_accuracy?: number;
  minimum_recommendation_acceptance?: number;
  minimum_reviewed_cases?: number;
  minimum_validation_success?: number;
  version: string;
}

export interface CalibrationCorpusSummary {
  case_count: number;
  corpus_fingerprint: string;
  corpus_key: string;
  evaluated_at: string;
  evaluation_fingerprint: string;
  id: string;
  metrics_source_version: string;
  observed_metrics: CalibrationObservedMetrics;
  promotion_failures: Array<string>;
  promotion_passed: boolean;
  version: string;
}

export interface CalibrationObservedMetrics {
  affected_scope_mae?: number | null;
  candidate_precision?: number | null;
  effort_accuracy?: number | null;
  recommendation_acceptance?: number | null;
  reviewed_cases: number;
  validation_success?: number | null;
}

export interface CanvasBandLayoutModel {
  cells: Array<CanvasCellLayoutModel>;
  columns: number;
  domain_key: "experience" | "application" | "integration" | "data" | "platform" | "delivery";
  order: number;
}

export interface CanvasBindingModel {
  keys?: Array<string>;
  kind: "CAPABILITY" | "CATEGORY" | "RESOURCE_KIND" | "ENTITY_TYPE" | "ARCHITECTURE_ROLE" | "UNBOUND";
  reason?: string | null;
}

export interface CanvasCellComparisonModel {
  actual_state: "POPULATED" | "EMPTY" | "NOT_APPLICABLE" | "UNOBSERVED" | "UNBOUND";
  allowed_in_use: number;
  baseline_state: "POPULATED" | "EMPTY" | "NOT_APPLICABLE" | "UNOBSERVED" | "UNBOUND";
  cell_key: string;
  discouraged_in_use: number;
  preferred_in_use: number;
  prohibited_in_use: number;
  required_but_absent: boolean;
  unevaluable: boolean;
  ungoverned_in_use: number;
}

export interface CanvasCellLayoutModel {
  cell_key: string;
  span?: 1 | 2 | 3;
}

export interface CanvasCellMeasuresModel {
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  conformance: MeasureResultModel;
  coverage: MeasureResultModel;
  currency: MeasureResultModel;
  method_version: string;
  missing_inputs: Array<string>;
  overall_score?: number | null;
  posture_band?: "STRONG" | "ADEQUATE" | "WEAK" | "AT_RISK" | null;
  risk: MeasureResultModel;
  standardisation: MeasureResultModel;
}

export interface CanvasCellProjectionModel {
  cell_key: string;
  citations: Array<Citation>;
  expectation: CellExpectationModel;
  insight_refs: Array<string>;
  measures?: CanvasCellMeasuresModel | null;
  observation: CellObservationStatusModel;
  occupant_total: number;
  occupants: Array<CanvasOccupantModel>;
  policy?: TenantCellPolicyModel | null;
  state: "POPULATED" | "EMPTY" | "NOT_APPLICABLE" | "UNOBSERVED" | "UNBOUND";
  state_reason: string;
  unique_technology_total: number;
}

export interface CanvasClassificationTrayItemModel {
  citations: Array<Citation>;
  detail: string;
  entity: EntitySummary;
  reason: "UNCLASSIFIED" | "AMBIGUOUS" | "UNRESOLVED_POLICY" | "FILTERED";
}

export interface CanvasClassificationTrayModel {
  ambiguous_count: number;
  filtered_count: number;
  items: Array<CanvasClassificationTrayItemModel>;
  total_count: number;
  truncated: boolean;
  unclassified_count: number;
  unresolved_policy_count: number;
}

export interface CanvasComparison {
  actual_projection_fingerprint: string;
  baseline_projection_fingerprint: string;
  cells: Array<CanvasCellComparisonModel>;
  comparison_kind: "ACTUAL_TO_TARGET" | "ACTUAL_TO_ACTUAL";
  contract_version?: "1.0.0";
  input_fingerprint: string;
  method_version: string;
  summary: CanvasComparisonSummaryModel;
}

export interface CanvasComparisonRequest {
  actual: CanvasProjectionSelectorModel;
  baseline: CanvasProjectionSelectorModel;
  comparison_kind: "ACTUAL_TO_TARGET" | "ACTUAL_TO_ACTUAL" | "TIME_TO_TIME";
  reference_model_key?: string;
  template_key?: string;
}

export interface CanvasComparisonSummaryModel {
  aligned_cells: number;
  cells_with_violations: number;
  compared_cells: number;
  required_but_absent_cells: number;
  unevaluable_cells: number;
  ungoverned_cells: number;
}

export interface CanvasOccupantModel {
  adoption_applications: number;
  adoption_deployments: number;
  adoption_repositories: number;
  citations?: Array<Citation>;
  classification: "CURATED" | "CATALOG_MATCH" | "DETERMINISTIC" | "UNCLASSIFIED";
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  placement_keys: Array<string>;
  policy_reference?: string | null;
  policy_status: "PREFERRED" | "ALLOWED" | "DISCOURAGED" | "PROHIBITED" | "EXEMPTED" | "UNGOVERNED";
  technology: EntitySummary;
}

export interface CanvasPolicyExceptionModel {
  effective_from?: string | null;
  effective_to?: string | null;
  key: string;
  rationale: string;
  subject_ids: Array<string>;
}

export interface CanvasProjection {
  as_of: string;
  cells: Array<CanvasCellProjectionModel>;
  classification_tray: CanvasClassificationTrayModel;
  contract_version?: "1.0.0";
  input_fingerprint: string;
  method_version: string;
  reference_model_content_hash: string;
  reference_model_key: string;
  reference_model_version: string;
  scope: "ESTATE" | "APPLICATION" | "REPOSITORY" | "TARGET";
  subject?: EntitySummary | null;
  summary: CanvasProjectionSummaryModel;
  taxonomy_content_hash: string;
  taxonomy_key: string;
  taxonomy_version: string;
  template_key: string;
  template_version: string;
  tenant_profile_fingerprint?: string | null;
}

export interface CanvasProjectionSelectorModel {
  scope: "ESTATE" | "APPLICATION" | "REPOSITORY" | "TARGET";
  subject_id?: string | null;
}

export interface CanvasProjectionSummaryModel {
  adequate: number;
  at_risk: number;
  cells_with_violations: number;
  empty_cells: number;
  governed_cells: number;
  not_applicable_cells: number;
  populated_cells: number;
  strong: number;
  technology_cell_placements: number;
  unbound_cells: number;
  unique_technologies: number;
  unobserved_cells: number;
  weak: number;
}

export interface CanvasScopeSelectorModel {
  application_ids?: Array<string>;
  repository_ids?: Array<string>;
  tags?: Array<string>;
}

export interface CanvasTemplateList {
  contract_version?: "1.0.0";
  templates: Array<CanvasTemplateModel>;
}

export interface CanvasTemplateModel {
  bands: Array<CanvasBandLayoutModel>;
  content_hash: string;
  contract_version?: "1.0.0";
  key: string;
  name: string;
  reference_model_key: string;
  reference_model_version: string;
  version: string;
}

export interface CapabilityBandModel {
  band: "READ" | "EXECUTE" | "CONDITIONAL" | "PROHIBITED" | "ESCALATE";
  operations?: Array<CapabilityEnvelopeOperation>;
}

export interface CapabilityDefinitionModel {
  aliases?: Array<string>;
  description: string;
  key: string;
  name: string;
  parent_key?: string | null;
}

export interface CapabilityEnvelopeCompileRequest {
  context_confidence: number;
  environment: string;
  estate_watermark: string;
  evidence_fact_ids?: Array<string>;
  objective: string;
  operations: Array<AgentOperationRequest>;
  risk_tier: "TIER_0" | "TIER_1" | "TIER_2" | "TIER_3";
  subject_entity_ids?: Array<string>;
  ttl_seconds?: number | null;
}

export interface CapabilityEnvelopeModel {
  actor_key: string;
  bands: Array<CapabilityBandModel>;
  compiled_hash: string;
  constraints?: Record<string, unknown>;
  context_confidence: number;
  contract_version?: "1.0.0";
  contradiction_ids?: Array<string>;
  created_at: string;
  decision: "ALLOW" | "CONSTRAIN" | "ESCALATE" | "DENY";
  decision_reasons?: Array<GateReason>;
  environment: string;
  estate_watermark: string;
  evidence_fact_ids?: Array<string>;
  id: string;
  objective: string;
  risk_tier: "TIER_0" | "TIER_1" | "TIER_2" | "TIER_3";
  status: "ACTIVE" | "EXPIRED" | "REVOKED" | "CONSUMED";
  valid_until: string;
}

export interface CapabilityEnvelopeOperation {
  band: "READ" | "EXECUTE" | "CONDITIONAL" | "PROHIBITED" | "ESCALATE";
  constraints?: Record<string, unknown>;
  operation_key: string;
}

export interface CapabilityFootprintList {
  as_of: string;
  contract_version?: "1.0.0";
  footprints: Array<CapabilityFootprintModel>;
}

export interface CapabilityFootprintModel {
  application_count: number;
  capability: EntitySummary;
  repository_count: number;
  reuse_signal: number;
  technology_count: number;
  technology_counts: Record<string, number>;
  technology_entropy: number;
}

export interface CapabilityInferenceReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface CapabilityInferenceReviewResult {
  capability_inference_id: string;
  contract_version?: "1.0.0";
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface CapabilityInferenceSummary {
  analyzer: Extractor;
  assertion_class: "CURATED" | "INFERRED";
  capability: CapabilityDefinitionModel;
  confidence: number;
  confidence_band: "HIGH" | "MEDIUM" | "LOW";
  counter_evidence_fact_ids: Array<string>;
  created_at: string;
  id: string;
  model_name?: string | null;
  model_provider?: string | null;
  policy_version: string;
  rationale: string;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_revision: string;
  stale: boolean;
  subject: EntitySummary;
  supporting_fact_ids: Array<string>;
  taxonomy_key: string;
  taxonomy_version: string;
  version: number;
}

export interface CapabilityTaxonomyResponse {
  capabilities: Array<CapabilityDefinitionModel>;
  content_hash: string;
  contract_version?: "1.0.0";
  description: string;
  key: string;
  name: string;
  version: string;
}

export interface CellExpectationModel {
  allowed_diversity?: number | null;
  applicability?: "REQUIRED" | "RECOMMENDED" | "OPTIONAL" | "NOT_APPLICABLE";
  maximum_implementations?: number | null;
  minimum_implementations?: number | null;
}

export interface CellObservationStatusModel {
  fresh_subjects: number;
  in_scope_subjects: number;
  input_fingerprint: string;
  method_version: string;
  missing_inputs: Array<string>;
  observed_subjects: number;
  required_sensor_kinds: Array<string>;
  status: "COMPLETE" | "PARTIAL" | "MISSING" | "NOT_APPLICABLE";
  supported_sensor_kinds: Array<string>;
}

export interface ChangeGate {
  reasons?: Array<GateReason>;
  state: "BLOCKED" | "ESCALATE" | "CONSTRAIN" | "CLEAR";
}

export interface ChangeScope {
  affected_count: number;
  component_path?: string | null;
  entity_id?: string | null;
  evidence_fact_ids: Array<string>;
  id: string;
  kind: "ESTATE" | "REPOSITORY" | "COMPONENT";
  label: string;
  version_distribution: Array<VersionDistribution>;
}

export interface ChangeScopeList {
  contract_version?: "1.0.0";
  policy_version: string;
  scopes: Array<ChangeScope>;
  subject: EntitySummary;
}

export interface ChangeSetCompileRequest {
  atomic?: boolean;
  entry_point?: "API" | "PULL_REQUEST" | "CHANGE_TICKET" | "ARCHITECTURE_CHANGE" | "AGENT_PROPOSAL";
  external_reference?: string | null;
  idempotency_key: string;
  mutations: Array<ChangeSetMutationRequest>;
}

export interface ChangeSetModel {
  atomic?: boolean;
  created_at?: string | null;
  id?: string | null;
  input_fingerprint: string;
  lifecycle: "DRAFT" | "VALIDATED" | "REJECTED" | "SUPERSEDED" | "SUBMITTED" | "EXECUTED" | "CANCELLED";
  mutations: Array<MutationIR>;
  schema_version?: "changeset/1.0.0";
}

export interface ChangeSetMutationRequest {
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  scope_id?: string | null;
  subject_id?: string | null;
  subject_query?: string | null;
  target_version?: string | null;
}

export interface Citation {
  fact_id: string;
  href?: string | null;
  label: string;
}

export interface CodePolicyTechnologySummary {
  category_key?: string | null;
  classification: "CURATED" | "CATALOG_MATCH" | "DETERMINISTIC" | "UNCLASSIFIED";
  detected_repository_count: number;
  domain_key?: string | null;
  technology: EntitySummary;
}

export interface CodePolicyViolation {
  fact_ids: Array<string>;
  function_key: string;
  function_name: string;
  matched_technology_id: string;
  message: string;
  rule: "PROHIBITED" | "NOT_ALLOWED";
  technology: EntitySummary;
}

export interface ComponentProfile {
  classifications?: Array<string>;
  component_path?: string | null;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  evidence_fact_ids?: Array<string>;
  freshness: Freshness;
  independently_deployable?: boolean | null;
  limitations?: Array<GateReason>;
  runtime?: string | null;
  status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
}

export interface Connector {
  created_at: string;
  display_name: string;
  external_account_key?: string;
  id: string;
  last_error?: string | null;
  last_synced_at?: string | null;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  scopes?: Array<string>;
  status: "CONNECTED" | "NEEDS_REAUTH" | "DISABLED" | "REVOKED";
  updated_at: string;
}

export interface ConnectorList {
  connectors: Array<Connector>;
  contract_version?: "1.0.0";
}

export interface ConnectorRegisterRequest {
  credential_reference?: string;
  display_name: string;
  external_account_key?: string;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  scopes?: Array<string>;
}

export interface ConnectorUpdateRequest {
  credential_reference?: string | null;
  display_name?: string | null;
  scopes?: Array<string> | null;
  status?: "CONNECTED" | "NEEDS_REAUTH" | "DISABLED" | "REVOKED" | null;
}

export interface ContainerCompositionList {
  as_of: string;
  contract_version?: "1.0.0";
  images: Array<ContainerImageComposition>;
  limitations?: Array<GateReason>;
  repository: EntitySummary;
  status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
}

export interface ContainerImageComposition {
  architecture?: string | null;
  evidence_fact_ids?: Array<string>;
  freshness: Freshness;
  identity: ContainerImageIdentity;
  image: EntitySummary;
  layers?: Array<ContainerLayer>;
  limitations?: Array<GateReason>;
  operating_system?: string | null;
  packages?: Array<ContainerPackage>;
  scan_status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
}

export interface ContainerImageIdentity {
  canonical_reference?: string | null;
  digest?: string | null;
  observed_tags?: Array<string>;
  registry?: string | null;
  state: "RESOLVED" | "INFERRED" | "UNRESOLVED";
}

export interface ContainerLayer {
  command?: string | null;
  digest?: string | null;
  index: number;
  size_bytes?: number | null;
}

export interface ContainerPackage {
  ecosystem?: string | null;
  name: string;
  version?: string | null;
}

export interface ContradictionClaim {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  claim_key: string;
  confidence: number;
  display_value: string;
  evidence_fact_ids: Array<string>;
  observed_at: string;
  source_key: string;
}

export interface ContradictionLedger {
  as_of: string;
  contract_version?: "1.0.0";
  contradictions: Array<ContradictionLedgerItem>;
  limitations?: Array<GateReason>;
  method_version?: "current-fact-disagreement/1.0.0" | "assumption-registry/1.0.0";
  page_info: PageInfo;
}

export interface ContradictionLedgerItem {
  affected_entity_count: number;
  claims: Array<ContradictionClaim>;
  id: string;
  last_verified_at: string;
  limitations?: Array<GateReason>;
  predicate: string;
  status?: "OPEN";
  subject: EntitySummary;
  version?: number;
}

export interface ContradictionResolveRequest {
  expected_version: number;
  rationale: string;
  status: "RESOLVED" | "DISMISSED";
}

export interface Coverage {
  facts_with_evidence_ratio: number;
  repositories_scanned: number;
  repositories_total: number;
}

export interface CriticalGraphEdge {
  components?: Record<string, unknown>;
  fact_id: string;
  limitations?: Array<Record<string, unknown>>;
  metric_key?: string;
  score: number;
  source: EntitySummary;
  supporting_fact_ids: Array<string>;
  target: EntitySummary;
}

export interface CriticalGraphEdgeList {
  as_of: string;
  contract_version?: "1.0.0";
  edges?: Array<CriticalGraphEdge>;
  entity: EntitySummary;
  limitations?: Array<Record<string, unknown>>;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface DeploymentAction {
  target: string;
  target_kind?: string | null;
  verb: string;
}

export interface DeploymentProfile {
  actions?: Array<DeploymentAction>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  deployment: EntitySummary;
  environment?: string | null;
  evidence_fact_ids?: Array<string>;
  freshness: Freshness;
  limitations?: Array<GateReason>;
  provider?: string | null;
  region?: string | null;
  status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
  workload_kind?: string | null;
}

export interface DeploymentProfileList {
  as_of: string;
  contract_version?: "1.0.0";
  limitations?: Array<GateReason>;
  profiles: Array<DeploymentProfile>;
  repository: EntitySummary;
}

export interface DeterministicInsight {
  affected_application_count: number;
  affected_deployment_count: number;
  affected_repositories: Array<EntitySummary>;
  affected_repository_count: number;
  detected_at: string;
  evidence_coverage: number;
  id: string;
  input_fingerprint: string;
  kind: "VULNERABLE_DIRECT_DEPENDENCY" | "VULNERABLE_TRANSITIVE_DEPENDENCY" | "DEPRECATED_DEPENDENCY" | "UNUSED_DIRECT_DEPENDENCY" | "VERSION_FRAGMENTATION" | "CAPABILITY_DIVERSITY" | "DEPENDENCY_CONFUSION" | "LICENSE_OBLIGATION" | "CROSS_REPOSITORY_CLONE" | "VENDORED_SOURCE_OUTSIDE_MANAGEMENT" | "MISSING_README" | "MISSING_LICENSE" | "MISSING_CODEOWNERS" | "MISSING_CI_CONFIGURATION" | "MISSING_DEPENDENCY_LOCKFILE" | "MISSING_TESTS";
  missing_inputs: Array<string>;
  priority_score: number;
  recommendation?: DeterministicInsightRecommendation | null;
  rule_key: string;
  rule_version: string;
  scope_entity_ids: Array<string>;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
  stages: InsightImpactStages;
  subject: EntitySummary;
  summary: string;
  supporting_fact_ids: Array<string>;
  title: string;
}

export interface DeterministicInsightGovernanceState {
  active_rule_count: number;
  contract_version?: "1.0.0";
  evidence_coverage: number;
  finding_count: number;
  last_evaluated_at: string;
  method_version: string;
  needs_data_rule_count: number;
  rules: Array<DeterministicInsightRuleSummary>;
}

export interface DeterministicInsightList {
  as_of: string;
  contract_version?: "1.0.0";
  insights: Array<DeterministicInsight>;
  page_info: PageInfo;
  summary: DeterministicInsightSummary;
}

export interface DeterministicInsightRecommendation {
  action: "UPGRADE" | "REMOVE" | "CONSOLIDATE" | "REPLACE" | "INVESTIGATE";
  estimated_effort: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  rationale: string;
  target?: EntitySummary | null;
  title: string;
}

export interface DeterministicInsightRuleSummary {
  configuration: Record<string, unknown>;
  description: string;
  enabled: boolean;
  finding_count: number;
  minimum_repositories: number;
  missing_inputs: Array<string>;
  name: string;
  phase: 1 | 2 | 3;
  readiness: "ACTIVE" | "NEEDS_DATA";
  rule_key: string;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
  updated_at?: string | null;
  updated_by?: string | null;
  version: number;
}

export interface DeterministicInsightRuleUpdateRequest {
  configuration?: Record<string, unknown>;
  enabled: boolean;
  expected_version?: number;
  minimum_repositories?: number;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
}

export interface DeterministicInsightSummary {
  affected_repositories: number;
  critical: number;
  deployed: number;
  high: number;
  runtime_observed: number;
  total: number;
}

export interface DuplicateCapabilityCandidateSummary {
  capability: CapabilityDefinitionModel;
  capability_inference_ids: Array<string>;
  confidence: number;
  dependencies: Array<EntitySummary>;
  id: string;
  limitations: Array<string>;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_revision: string;
  stale: boolean;
  summary: string;
  supporting_fact_ids: Array<string>;
  version: number;
}

export interface DuplicateCapabilityReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface DuplicateCapabilityReviewResult {
  contract_version?: "1.0.0";
  duplicate_capability_candidate_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface EcosystemAdmissionEvaluateRequest {
  minimum_dependency_share?: number;
  minimum_repositories?: number;
}

export interface EcosystemAdmissionSummary {
  calibration_gate_passed: boolean;
  decided_at?: string | null;
  decided_by?: string | null;
  decision_fingerprint: string;
  ecosystem: "PYPI" | "MAVEN" | "CARGO" | "NUGET";
  metadata_parity: boolean;
  minimum_dependency_share: number;
  minimum_repositories: number;
  observed_dependency_share: number;
  observed_repositories: number;
  predecessor_admitted: boolean;
  reasons: Array<string>;
  sequence: number;
  status: "NOT_EVALUATED" | "PROPOSED" | "ADMITTED" | "RETIRED" | "STALE";
}

export interface EmbeddingBackfillRequest {
  embedding_space_id?: string | null;
  entity_ids?: Array<string>;
  entity_types?: Array<string>;
  limit?: number;
}

export interface EmbeddingBackfillResult {
  embedding_space_id: string;
  queued_jobs: number;
  requested_at: string;
}

export interface EmbeddingSpacePromotionRequest {
  action?: "PROMOTE" | "ROLLBACK";
}

export interface EmbeddingSpacePromotionResult {
  action: "PROMOTE" | "ROLLBACK";
  activated_at: string;
  embedding_space_id: string;
  space_kind: "SEMANTIC_ENTITY" | "STRUCTURAL_GRAPH" | "CODE";
}

export interface EmbeddingSpaceSnapshot {
  coverage_ratio: number;
  dimensions: number;
  evaluation?: Record<string, unknown>;
  id: string;
  lifecycle_state: "SHADOW" | "ACTIVE" | "RETIRED" | "FAILED";
  model_or_algorithm: string;
  provider: string;
  space_key: string;
  space_kind: "SEMANTIC_ENTITY" | "STRUCTURAL_GRAPH" | "CODE";
  template_version: string;
  updated_at: string;
}

export interface EmbeddingStatus {
  active_spaces?: Array<EmbeddingSpaceSnapshot>;
  as_of: string;
  contract_version?: "1.0.0";
  enabled: boolean;
  failed_jobs: number;
  limitations?: Array<Record<string, unknown>>;
  model: string;
  pending_jobs: number;
  provider: string;
  running_jobs: number;
  shadow_spaces?: Array<EmbeddingSpaceSnapshot>;
}

export interface EnterpriseInsightReport {
  answerable: boolean;
  category: "ENTERPRISE_RISK" | "TECHNOLOGY_RATIONALIZATION" | "PORTFOLIO_DECISIONS";
  confidence?: number | null;
  evidence_count: number;
  key: string;
  metric_label: string;
  metric_value: string;
  question: string;
  response: AskResponse;
  status: "ACTION_REQUIRED" | "WATCH" | "HEALTHY" | "WAITING_FOR_DATA";
  summary: string;
  title: string;
}

export interface EnterpriseInsightReportList {
  answerable_reports: number;
  contract_version?: "1.0.0";
  evaluated_at: string;
  method_version: string;
  reports: Array<EnterpriseInsightReport>;
  total_reports: number;
}

export interface EntityDescriptionUpdateRequest {
  description: string;
}

export interface EntityGraphIntelligence {
  as_of: string;
  community_keys?: Array<string>;
  contract_version?: "1.0.0";
  entity: EntitySummary;
  limitations?: Array<Record<string, unknown>>;
  metrics?: Array<GraphMetric>;
  primary_status: "STRUCTURALLY_CRITICAL" | "ELEVATED" | "TYPICAL" | "WAITING_FOR_DATA";
  reasons?: Array<string>;
  snapshots?: Array<GraphAnalysisSnapshot>;
}

export interface EntityResolution {
  candidates?: Array<ResolutionCandidate>;
  confidence: number;
  entity?: EntitySummary | null;
  evidence_fact_ids?: Array<string>;
  method: string;
  method_version: string;
  state: "RESOLVED" | "INFERRED" | "UNRESOLVED";
}

export interface EntitySummary {
  canonical_key?: string | null;
  id: string;
  kind: string;
  name: string;
  summary?: string | null;
}

export interface EstateComponentDetail {
  as_of: string;
  component: EstateComponentSummary;
  container_images?: Array<EntitySummary>;
  contract_version?: "1.0.0";
  deployments?: Array<EntitySummary>;
  limitations?: Array<GateReason>;
  technologies?: Array<EntitySummary>;
}

export interface EstateComponentList {
  as_of: string;
  components: Array<EstateComponentSummary>;
  contract_version?: "1.0.0";
  limitations?: Array<GateReason>;
  page_info: PageInfo;
}

export interface EstateComponentSummary {
  component: EntitySummary;
  profile: ComponentProfile;
  repository?: EntitySummary | null;
}

export interface EstateCounts {
  applications: number;
  repositories: number;
  services: number;
  technologies: number;
}

export interface EstateLineageEdgeModel {
  confidence: number;
  downstream: EntitySummary;
  evidence_fact_id: string;
  id: string;
  lineage_kind: "COLUMN_TO_TABLE" | "TABLE_TO_PIPELINE" | "PIPELINE_TO_FEATURE" | "FEATURE_TO_MODEL" | "MODEL_TO_AGENT" | "AGENT_TO_API" | "API_TO_PROCESS" | "DATASET_TO_CAPABILITY" | "OTHER";
  observed_at: string;
  upstream: EntitySummary;
}

export interface EstateLineageList {
  contract_version?: "1.0.0";
  edges: Array<EstateLineageEdgeModel>;
  limitations?: Array<GateReason>;
  page_info: PageInfo;
}

export interface EstateStrata {
  as_of: string;
  contract_version?: "1.0.0";
  layers: Array<EstateStratumLayer>;
  method_version?: "estate-strata/1.0.0";
}

export interface EstateStratumLayer {
  as_of?: string | null;
  corroboration_ratio?: number | null;
  coverage_ratio?: number | null;
  key: "BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "AI";
  label: string;
  limitations?: Array<GateReason>;
  observed_count?: number | null;
  population_count?: number | null;
  status: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED";
}

export interface EstateSummary {
  as_of: string;
  contract_version?: "1.0.0";
  counts: EstateCounts;
  coverage: Coverage;
  distributions: Record<string, number>;
  limitations?: Array<Record<string, unknown>>;
  page_info?: PageInfo | null;
  ranked_items: Array<RankedItem>;
}

export interface EvidenceDetail {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  closed_at?: string | null;
  confidence: number;
  contract_version?: "1.0.0";
  effective_at?: string | null;
  evidence: Array<Record<string, unknown>>;
  extractor: Extractor;
  fact_id: string;
  observed_at: string;
  predicate: string;
  properties?: Record<string, unknown> | null;
  source_revision: string;
}

export interface Extractor {
  key: string;
  version: string;
}

export interface FlightEventCreateRequest {
  event_type: "OBJECTIVE" | "CONTEXT" | "TOOL" | "CALL" | "DECISION" | "ACTION" | "ASSET" | "VERIFICATION" | "OUTCOME";
  occurred_at: string;
  payload: Record<string, unknown>;
  system_boundary: string;
}

export interface FlightEventModel {
  event_hash: string;
  event_type: "OBJECTIVE" | "CONTEXT" | "TOOL" | "CALL" | "DECISION" | "ACTION" | "ASSET" | "VERIFICATION" | "OUTCOME";
  id: string;
  occurred_at: string;
  payload: Record<string, unknown>;
  previous_hash?: string | null;
  recorded_at: string;
  sequence: number;
  system_boundary: string;
}

export interface FlightRecordCreateRequest {
  envelope_id: string;
  objective: string;
}

export interface FlightRecordFinalizeRequest {
  outcome: Record<string, unknown>;
  status: "SUCCEEDED" | "FAILED" | "ABORTED";
}

export interface FlightRecordModel {
  chain_head?: string | null;
  completed_at?: string | null;
  contract_version?: "1.0.0";
  envelope_id: string;
  event_count: number;
  events?: Array<FlightEventModel>;
  id: string;
  objective: string;
  outcome?: Record<string, unknown> | null;
  started_at: string;
  started_by: string;
  status: "ACTIVE" | "SUCCEEDED" | "FAILED" | "ABORTED";
}

export interface Freshness {
  effective_at?: string | null;
  observed_at: string;
  source_key?: string | null;
  status: "FRESH" | "STALE" | "UNKNOWN";
}

export interface GateReason {
  code: string;
  evidence_fact_ids?: Array<string>;
  message: string;
}

export interface GitHubInstallationConnectRequest {
  display_name?: string | null;
  installation_id: string;
  pilot_manual_binding_acknowledged: true;
}

export interface GitHubInstallationSetupRequest {
  return_to?: string;
}

export interface GitHubInstallationSetupResponse {
  expires_at: string;
  setup_url: string;
}

export interface GitHubRepositoryConnectRequest {
  credential_reference?: "env://GITHUB_TOKEN";
  repository: string;
}

export interface GitHubRepositoryOption {
  archived?: boolean;
  default_branch?: string | null;
  full_name: string;
  visibility: "public" | "private" | "internal";
}

export interface GitHubRepositoryOptionList {
  contract_version?: "1.0.0";
  repositories: Array<GitHubRepositoryOption>;
  token_configured: boolean;
  truncated?: boolean;
}

export interface GitHubTokenConfiguration {
  configured?: boolean;
  contract_version?: "1.0.0";
  fingerprint?: string | null;
  source?: "TENANT_SECRET" | "ENVIRONMENT" | "NONE";
  updated_at?: string | null;
  updated_by?: string | null;
}

export interface GitHubTokenUpdateRequest {
  token: string;
}

export interface GraphAnalysisRequestCreate {
  policy_key?: string;
  reason?: string;
}

export interface GraphAnalysisRequestResult {
  created_at: string;
  id: string;
  policy_key: string;
  requested_change_watermark: number;
  status: "PENDING" | "WAITING_FOR_PROJECTION";
}

export interface GraphAnalysisSnapshot {
  analysis_run_id: string;
  as_of: string;
  coverage?: Record<string, unknown>;
  edge_count: number;
  limitations?: Array<Record<string, unknown>>;
  neo4j_projection_watermark: number;
  node_count: number;
  policy_hash: string;
  policy_key: string;
  policy_version: number;
  requested_change_watermark: number;
  status: "SUCCEEDED" | "SUCCEEDED_WITH_LIMITATIONS";
}

export interface GraphAnomaly {
  anomaly_key: string;
  cohort_key: string;
  cohort_size: number;
  entity: EntitySummary;
  id: string;
  limitations?: Array<Record<string, unknown>>;
  observed_components?: Record<string, unknown>;
  percentile: number;
  reasons?: Array<string>;
  score: number;
  supporting_fact_ids?: Array<string>;
}

export interface GraphAnomalyList {
  anomalies?: Array<GraphAnomaly>;
  as_of: string;
  contract_version?: "1.0.0";
  limitations?: Array<Record<string, unknown>>;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface GraphBlastRadius {
  affected_entity_count: number;
  as_of: string;
  contract_version?: "1.0.0";
  entity: EntitySummary;
  impacts?: Array<GraphImpactPath>;
  limitations?: Array<Record<string, unknown>>;
  maximum_depth: number;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface GraphCommunity {
  community_key: string;
  member_count: number;
  representative_entities?: Array<EntitySummary>;
}

export interface GraphCommunityList {
  algorithm_key: string;
  as_of: string;
  communities?: Array<GraphCommunity>;
  contract_version?: "1.0.0";
  limitations?: Array<Record<string, unknown>>;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface GraphEdge {
  assertion_class: "DECLARED" | "OBSERVED" | "INFERRED" | "CURATED" | "EXTERNAL_MEASURED";
  citation_fact_ids: Array<string>;
  confidence: number;
  id: string;
  is_bridge?: boolean | null;
  predicate: string;
  review_state: "CONFIRMED" | "POSSIBLE" | "REJECTED" | "NOT_APPLICABLE";
  source: string;
  target: string;
}

export interface GraphImpactPath {
  distance: number;
  entity_ids: Array<string>;
  minimum_confidence: number;
  supporting_fact_ids: Array<string>;
  target: EntitySummary;
}

export interface GraphIntelligenceStatus {
  as_of: string;
  contract_version?: "1.0.0";
  deployment_state: "PROVISIONING" | "ACTIVE" | "SUSPENDED" | "ERROR" | "UNCONFIGURED";
  desired_change_watermark: number;
  failed_requests: number;
  limitations?: Array<Record<string, unknown>>;
  neo4j_projection_watermark: number;
  oldest_pending_at?: string | null;
  pending_requests: number;
  projection_lag: number;
  running_requests: number;
  snapshots?: Array<GraphAnalysisSnapshot>;
}

export interface GraphMetric {
  analysis_run_id: string;
  components?: Record<string, unknown>;
  limitations?: Array<Record<string, unknown>>;
  metric_key: string;
  numeric_value?: number | null;
  percentile?: number | null;
  policy_key: string;
  rank?: number | null;
}

export interface GraphMotif {
  components?: Record<string, unknown>;
  id: string;
  limitations?: Array<Record<string, unknown>>;
  members: Array<EntitySummary>;
  minimum_confidence: number;
  motif_key: string;
  supporting_fact_ids: Array<string>;
}

export interface GraphMotifList {
  as_of: string;
  contract_version?: "1.0.0";
  limitations?: Array<Record<string, unknown>>;
  motifs?: Array<GraphMotif>;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface GraphNeighborhood {
  center_id: string;
  contract_version?: "1.0.0";
  edges: Array<GraphEdge>;
  highlighted_path?: Array<string> | null;
  nodes: Array<GraphNode>;
  truncated: boolean;
  truncation_reason?: string | null;
}

export interface GraphNode {
  aggregate: boolean;
  community_key?: string | null;
  confidence?: number | null;
  id: string;
  key: string;
  label: string;
  member_count?: number | null;
  namespace: "BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "INTELLIGENCE";
  structural_status?: "STRUCTURALLY_CRITICAL" | "ELEVATED" | "TYPICAL" | "WAITING_FOR_DATA" | null;
  systemic_risk?: number | null;
  type: string;
}

export interface GraphRiskItem {
  component_contributions?: Record<string, Record<string, unknown>>;
  component_metrics?: Array<GraphMetric>;
  entity: EntitySummary;
  impacted_applications?: Array<EntitySummary>;
  method_version?: string;
  reasons?: Array<string>;
  renormalized_families?: Array<string>;
  systemic_risk: number;
}

export interface GraphRiskList {
  as_of: string;
  contract_version?: "1.0.0";
  limitations?: Array<Record<string, unknown>>;
  page_info?: PageInfo | null;
  risks?: Array<GraphRiskItem>;
  snapshot?: GraphAnalysisSnapshot | null;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface IdentityReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface IdentityReviewResult {
  contract_version?: "1.0.0";
  identity_assertion_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface InsightImpactStages {
  business_critical?: number | null;
  deployed: number;
  externally_exposed?: number | null;
  present: number;
  production?: number | null;
  referenced: number;
  runtime_observed: number;
  statically_reachable: number;
}

export interface InternalCatalogCandidateSummary {
  affected_call_sites: number;
  affected_files: number;
  candidate_id: string;
  capability: string;
  capability_definition_id: string;
  component_entity_id: string;
  component_key: string;
  confidence: number;
  name: string;
  repository_name: string;
  supporting_fact_ids: Array<string>;
}

export interface InternalCatalogComponentSummary {
  catalog_fingerprint: string;
  component_key: string;
  governed_at?: string | null;
  governed_by?: string | null;
  id: string;
  name: string;
  owner?: string | null;
  review_state: "UNREVIEWED" | "APPROVED" | "REJECTED";
  status: "APPROVED" | "DEPRECATED" | "BLOCKED";
  supporting_fact_ids: Array<string>;
  version: string;
}

export interface InternalCatalogComponentUpsertRequest {
  api_symbols?: Array<string>;
  behavior_claims?: Array<Record<string, unknown>>;
  capability_definition_id: string;
  component_entity_id: string;
  decision: "APPROVE" | "REJECT";
  license?: string | null;
  owner: string;
  policy_tags?: Array<string>;
  runtime_constraints?: Record<string, string>;
  security_status?: "CLEAR" | "WARN" | "BLOCKED" | "UNKNOWN";
  status?: "APPROVED" | "DEPRECATED" | "BLOCKED";
  supporting_fact_ids: Array<string>;
  version: string;
}

export interface InternalUsage {
  application_count: number;
  repositories?: Array<EntitySummary> | null;
  repository_count: number;
}

export interface MeasureResultModel {
  inputs: Array<string>;
  method_version: string;
  status: "ELIGIBLE" | "INSUFFICIENT_DATA" | "NOT_APPLICABLE" | "NOT_CONFIGURED";
  supporting_fact_ids: Array<string>;
  value?: number | null;
}

export interface MemberInviteRequest {
  actor_key: string;
  display_name?: string;
  email?: string;
  role?: "view" | "review" | "execute" | "admin";
}

export interface MemberUpdateRequest {
  role?: "view" | "review" | "execute" | "admin" | null;
  status?: "INVITED" | "ACTIVE" | "SUSPENDED" | null;
}

export interface ModernizationCandidateModel {
  analyzer: Extractor;
  capability?: CapabilityDefinitionModel | null;
  confidence: number;
  counter_evidence_fact_ids: Array<string>;
  id: string;
  impact?: ModernizationImpactModel | null;
  kind: "DEPENDENCY_CONSOLIDATION" | "INTERNAL_DUPLICATION" | "VENDORED_DUPLICATION" | "NATIVE_REPLACEMENT";
  options: Array<ModernizationOptionModel>;
  recommendation?: ModernizationRecommendationModel | null;
  review_state: "UNREVIEWED" | "CONFIRMED" | "REJECTED";
  source_locations: Array<Record<string, unknown>>;
  source_revision: string;
  stale: boolean;
  subjects: Array<EntitySummary>;
  summary: string;
  supporting_fact_ids: Array<string>;
  validation_gaps: Array<string>;
  version: number;
}

export interface ModernizationCandidateReviewRequest {
  decision: "CONFIRM" | "REJECT";
  expected_version: number;
  rationale: string;
}

export interface ModernizationCandidateReviewResult {
  contract_version?: "1.0.0";
  modernization_candidate_id: string;
  review_state: "CONFIRMED" | "REJECTED";
  reviewed_at: string;
  version: number;
}

export interface ModernizationGovernanceState {
  active_calibration?: CalibrationCorpusSummary | null;
  active_policy?: ModernizationPolicySummary | null;
  contract_version?: "1.0.0";
  ecosystem_admissions: Array<EcosystemAdmissionSummary>;
  internal_component_candidates?: Array<InternalCatalogCandidateSummary>;
  internal_components: Array<InternalCatalogComponentSummary>;
}

export interface ModernizationImpactModel {
  affected_call_sites: number;
  affected_files: number;
  affected_test_files: Array<string>;
  build_touchpoints: Array<Record<string, unknown>>;
  confidence: number;
  configuration_touchpoints: Array<Record<string, unknown>>;
  covered_call_sites: number;
  deployment_touchpoints: Array<Record<string, unknown>>;
  dynamic_signals: Array<string>;
  effort_model_version: string;
  effort_points: number;
  evidence_locations: Array<Record<string, unknown>>;
  limitations: Array<string>;
  uncovered_call_sites: number;
}

export interface ModernizationList {
  as_of: string;
  contract_version?: "1.0.0";
  opportunities: Array<RankedItem>;
  page_info: PageInfo;
}

export interface ModernizationOptionEligibilityModel {
  api_fit: "PASS" | "FAIL" | "UNKNOWN";
  behavior_fit: "PASS" | "FAIL" | "UNKNOWN";
  capability_fit: "PASS" | "FAIL" | "UNKNOWN";
  disqualifiers: Array<string>;
  eligible: boolean;
  evidence: Record<string, unknown>;
  license_fit: "PASS" | "FAIL" | "UNKNOWN";
  policy_fit: "PASS" | "FAIL" | "UNKNOWN";
  runtime_fit: "PASS" | "FAIL" | "UNKNOWN";
  security_fit: "PASS" | "FAIL" | "UNKNOWN";
  unknowns: Array<string>;
}

export interface ModernizationOptionModel {
  canonical_key: string;
  compatibility: "OBSERVED" | "COMPATIBLE" | "UNKNOWN" | "INCOMPATIBLE";
  disqualifiers: Array<string>;
  eligibility?: ModernizationOptionEligibilityModel | null;
  id: string;
  kind: "NATIVE" | "INTERNAL" | "UPGRADE" | "PACKAGE";
  name: string;
  rank: number;
  rationale: string;
  score: number;
  score_components: Record<string, number>;
  supporting_fact_ids: Array<string>;
  target_entity?: EntitySummary | null;
  tradeoffs: Array<string>;
  validation_gaps: Array<string>;
}

export interface ModernizationPolicyPublishRequest {
  allowed_licenses?: Array<string>;
  allowed_security_statuses?: Array<"CLEAR" | "WARN" | "BLOCKED" | "UNKNOWN">;
  denied_option_keys?: Array<string>;
  policy_key?: string;
  required_policy_tags?: Array<string>;
  runtime_versions?: Record<string, string>;
  version: string;
}

export interface ModernizationPolicySummary {
  activated_at: string;
  activated_by: string;
  allowed_licenses: Array<string>;
  allowed_security_statuses: Array<string>;
  configuration_fingerprint: string;
  denied_option_keys: Array<string>;
  id: string;
  policy_key: string;
  required_policy_tags: Array<string>;
  runtime_versions: Record<string, string>;
  status: "DRAFT" | "ACTIVE" | "RETIRED";
  version: string;
}

export interface ModernizationRecommendationModel {
  action: "CONSOLIDATE" | "REPLACE" | "UPGRADE" | "REFACTOR" | "INVESTIGATE";
  affected_call_sites: number;
  affected_files: number;
  confidence: number;
  counter_evidence_fact_ids: Array<string>;
  counter_signals: Array<string>;
  created_at: string;
  estimated_effort: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  id: string;
  migration_plan: Array<string>;
  not_simulatable_reason?: Record<string, unknown> | null;
  objective: string;
  policy_version: string;
  proposed_change_set_id?: string | null;
  rationale: string;
  review_state: "UNREVIEWED" | "ACCEPTED" | "REJECTED" | "DISMISSED";
  rollback_plan: Array<string>;
  selected_option_id?: string | null;
  simulation_eligibility?: "ELIGIBLE" | "NOT_SIMULATABLE" | "UNKNOWN";
  stale: boolean;
  supporting_fact_ids: Array<string>;
  title: string;
  validation_gaps: Array<string>;
  version: number;
}

export interface ModernizationRecommendationReviewRequest {
  decision: "ACCEPT" | "REJECT" | "DISMISS";
  expected_version: number;
  rationale: string;
}

export interface ModernizationRecommendationReviewResult {
  contract_version?: "1.0.0";
  modernization_recommendation_id: string;
  review_state: "ACCEPTED" | "REJECTED" | "DISMISSED";
  reviewed_at: string;
  version: number;
}

export interface ModernizationScenarioItem {
  action: "CONSOLIDATE" | "REPLACE" | "UPGRADE" | "REFACTOR" | "INVESTIGATE";
  effort_points: number;
  policy_version: string;
  recommendation_id: string;
  repository: EntitySummary;
  score: number;
  score_components: Record<string, number>;
  selected: boolean;
  title: string;
}

export interface ModernizationScenarioRequest {
  budget_points: number;
  excluded_recommendation_ids?: Array<string>;
}

export interface ModernizationScenarioResult {
  as_of: string;
  budget_points: number;
  contract_version?: "1.0.0";
  items: Array<ModernizationScenarioItem>;
  total_score: number;
  used_points: number;
}

export interface ModernizationValidationOutcomeRequest {
  actual_call_sites?: number | null;
  actual_effort?: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN" | null;
  actual_files?: number | null;
  failed_checks?: Array<string>;
  notes: string;
  successful_checks?: Array<string>;
  validation_status: "SUCCEEDED" | "PARTIAL" | "FAILED";
}

export interface ModernizationValidationOutcomeResult {
  contract_version?: "1.0.0";
  id: string;
  modernization_recommendation_id: string;
  reported_at: string;
  validation_status: "SUCCEEDED" | "PARTIAL" | "FAILED";
}

export interface MutationCompileRequest {
  idempotency_key: string;
  intent?: string | null;
  predicate?: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE" | null;
  scope_id?: string | null;
  subject_id?: string | null;
  subject_query?: string | null;
  target_version?: string | null;
}

export interface MutationCompileResult {
  change_set?: ChangeSetModel | null;
  command_state: "EMPTY" | "RESOLVING" | "TOKENISED" | "COMPILED";
  contract_version?: "1.0.0";
  draft: MutationIR;
  gate: ChangeGate;
  replayed?: boolean;
}

export interface MutationIR {
  after: Record<string, unknown>;
  before: Record<string, unknown>;
  constraints?: Record<string, unknown>;
  id?: string | null;
  input_fingerprint: string;
  lifecycle: "DRAFT" | "VALIDATED" | "REJECTED" | "SUPERSEDED" | "SUBMITTED" | "EXECUTED" | "CANCELLED";
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  provenance: Record<string, unknown>;
  schema_version?: "mutation/1.0.0";
  scope?: ChangeScope | null;
  subject: EntityResolution;
  validation_errors?: Array<MutationValidationError>;
}

export interface MutationValidateRequest {
  change_set_id: string;
}

export interface MutationValidationError {
  code: string;
  evidence_fact_ids?: Array<string>;
  field: string;
  message: string;
}

export interface ObservedMutationCreateRequest {
  after: Record<string, unknown>;
  before: Record<string, unknown>;
  confidence: number;
  correlation_key: string;
  evidence_fact_ids: Array<string>;
  graph_watermark_before?: string | null;
  intervention_required?: boolean;
  observed_at: string;
  observed_impact: Record<string, unknown>;
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  predicted_simulation_run_id?: string | null;
  resolution?: string | null;
  rolled_back?: boolean;
  scope: Record<string, unknown>;
  source_kind: "PULL_REQUEST" | "COMMIT" | "DEPLOYMENT" | "TICKET" | "INCIDENT" | "POSTMORTEM" | "MANUAL";
  subject_entity_id: string;
  success?: boolean | null;
  unexpected_impact?: Record<string, unknown>;
}

export interface ObservedMutationList {
  contract_version?: "1.0.0";
  limitations?: Array<GateReason>;
  minimum_predictor_sample?: number;
  outcomes: Array<ObservedMutationModel>;
  page_info: PageInfo;
  similar_outcomes?: Array<ObservedMutationModel>;
  similarity_method?: "ENTITY_TYPE_AND_PREDICATE/1.0.0";
  subject: EntitySummary;
}

export interface ObservedMutationModel {
  after: Record<string, unknown>;
  before: Record<string, unknown>;
  confidence: number;
  correlation_key: string;
  created_at: string;
  evidence_fact_ids: Array<string>;
  graph_watermark_before?: string | null;
  id: string;
  input_fingerprint: string;
  intervention_required: boolean;
  observed_at: string;
  observed_impact: Record<string, unknown>;
  observed_impact_count?: number;
  predicate: "UPGRADE" | "REPLACE" | "REMOVE" | "DEPRECATE" | "MIGRATE" | "MOVE";
  predicted_finding_count?: number | null;
  predicted_simulation_run_id?: string | null;
  resolution?: string | null;
  rolled_back: boolean;
  scope: Record<string, unknown>;
  source_kind: string;
  subject: EntitySummary;
  success?: boolean | null;
  unexpected_impact: Record<string, unknown>;
  unexpected_impact_count?: number;
}

export interface PackageSource {
  freshness: Freshness;
  origin: string;
  registry_key: string;
  tenant_scoped: boolean;
  visibility: "PUBLIC" | "PRIVATE" | "UNKNOWN";
}

export interface PageInfo {
  has_next_page: boolean;
  next_cursor?: string | null;
}

export interface Phase3IntelligenceMetrics {
  affected_call_site_mae?: number | null;
  affected_files_mae?: number | null;
  as_of: string;
  candidate_counts: Record<string, number>;
  candidate_review_precision?: number | null;
  contract_version?: "1.0.0";
  dead_letter_count: number;
  effort_band_accuracy?: number | null;
  evidence_completeness_rate?: number | null;
  job_counts: Record<string, number>;
  job_latency_ms_p50?: number | null;
  job_latency_ms_p95?: number | null;
  model_cost_usd: number;
  model_invocation_count: number;
  model_latency_ms_p95?: number | null;
  queue_lag_seconds_p50?: number | null;
  queue_lag_seconds_p95?: number | null;
  recommendation_acceptance_rate?: number | null;
  recommendation_counts: Record<string, number>;
  retry_count: number;
  stale_candidate_count: number;
  stale_recommendation_count: number;
  successful_validation_rate?: number | null;
}

export interface ProviderQuota {
  backoff_until?: string | null;
  limit?: number | null;
  observed_at: string;
  provider: "GITHUB_APP" | "PACKAGE_REGISTRY" | "DEPS_DEV" | "OSV" | "OTHER";
  resets_at?: string | null;
  status: "OK" | "THROTTLED" | "EXHAUSTED";
  used: number;
}

export interface QuarantinedClaim {
  detail: string;
  reason: "UNCITED_OUTPUT" | "CITED_UNKNOWN_FINDING";
  values?: Array<string>;
}

export interface RankedItem {
  citations?: Array<Citation> | null;
  community_key?: string | null;
  dependency_depth?: number | null;
  dependency_tier?: number | null;
  domain: "BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "INTELLIGENCE";
  freshness: Freshness;
  id: string;
  kind: string;
  name: string;
  parent_application_id?: string | null;
  parent_application_name?: string | null;
  priority: Score;
  structural_status?: "STRUCTURALLY_CRITICAL" | "ELEVATED" | "TYPICAL" | "WAITING_FOR_DATA" | null;
  summary?: string | null;
  systemic_risk?: number | null;
  upstream_impact?: number | null;
  viability?: Score | null;
}

export interface RecommendationCompileRequest {
  idempotency_key?: string | null;
}

export interface RecommendationSummary {
  action: "RETAIN" | "UPGRADE" | "REMOVE" | "REPLACE" | "CONSOLIDATE" | "REFACTOR" | "REBUILD" | "REPLATFORM" | "RETIRE" | "INVESTIGATE";
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  counter_signals?: Array<string> | null;
  estimated_effort?: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN" | null;
  id: string;
  rationale: string;
  status: "PROPOSED" | "ACCEPTED" | "REJECTED" | "PLANNED" | "IN_PROGRESS" | "COMPLETED" | "DISMISSED";
  target?: EntitySummary | null;
  title: string;
}

export interface RepositoryActivity {
  contract_version?: "1.0.0";
  coverage: RepositoryActivityCoverage;
  events: Array<RepositoryActivityEvent>;
  freshness: Freshness;
  limitations?: Array<string>;
  page_info: PageInfo;
  repository: EntitySummary;
  source: RepositoryActivitySource;
  summary: RepositoryActivitySummary;
  top_contributors: Array<RepositoryActivityContributor>;
  window: "7d" | "30d" | "90d";
  window_ended_at: string;
  window_started_at: string;
}

export interface RepositoryActivityActor {
  actor_key: string;
  avatar_url?: string | null;
  classification?: "HUMAN" | "BOT" | "DEPENDENCY_BOT" | "CI_AUTOMATION" | "AI_AGENT" | "AI_ASSISTED_HUMAN" | "UNKNOWN";
  classification_basis?: string | null;
  classification_confidence?: number;
  is_bot?: boolean;
  login: string;
}

export interface RepositoryActivityContributor {
  actor: RepositoryActivityActor;
  commits: number;
  pull_requests_merged: number;
  total_events: number;
}

export interface RepositoryActivityCoverage {
  commits: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED" | "PERMISSION_REQUIRED" | "ERROR";
  contributors: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED" | "PERMISSION_REQUIRED" | "ERROR";
  deployments?: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED" | "PERMISSION_REQUIRED" | "ERROR";
  pull_requests: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED" | "PERMISSION_REQUIRED" | "ERROR";
  releases?: "AVAILABLE" | "PARTIAL" | "NOT_COLLECTED" | "PERMISSION_REQUIRED" | "ERROR";
}

export interface RepositoryActivityEvent {
  actor?: RepositoryActivityActor | null;
  branch?: string | null;
  event_type: "COMMIT" | "PULL_REQUEST_OPENED" | "PULL_REQUEST_MERGED" | "RELEASE" | "DEPLOYMENT" | "DEPENDENCY_CHANGE" | "ARCHITECTURE_CHANGE" | "INCIDENT" | "INTERVENTION" | "ROLLBACK";
  id: string;
  occurred_at: string;
  pull_request_number?: number | null;
  revision?: string | null;
  source_url?: string | null;
  title: string;
}

export interface RepositoryActivitySource {
  archived?: boolean | null;
  default_branch?: string | null;
  full_name?: string | null;
  provider?: "GITHUB";
  visibility?: "PUBLIC" | "PRIVATE" | "INTERNAL" | "UNKNOWN";
}

export interface RepositoryActivitySummary {
  commits?: number | null;
  contributors?: number | null;
  deployments?: number | null;
  last_change_at?: string | null;
  pull_requests_merged?: number | null;
  releases?: number | null;
}

export interface RepositoryCapabilityIntelligence {
  contract_version?: "1.0.0";
  duplicate_candidates: Array<DuplicateCapabilityCandidateSummary>;
  inferences: Array<CapabilityInferenceSummary>;
  repository: EntitySummary;
  taxonomy_key?: string | null;
  taxonomy_version?: string | null;
}

export interface RepositoryCodePolicyEvaluation {
  evaluated_at: string;
  evaluated_by: string;
  evidence_fingerprint: string;
  id: string;
  policy_set_fingerprint: string;
  repository: EntitySummary;
  status: "COMPLIANT" | "MISALIGNED" | "UNASSESSED" | "STALE";
  unclassified_technologies: Array<EntitySummary>;
  violations: Array<CodePolicyViolation>;
}

export interface RepositoryDetail {
  applications: Array<EntitySummary>;
  contract_version?: "1.0.0";
  deployments: Array<EntitySummary>;
  freshness: Freshness;
  graph_intelligence?: EntityGraphIntelligence | null;
  profile?: RepositoryProfile | null;
  repository: EntitySummary;
  technologies: Array<EntitySummary>;
}

export interface RepositoryFingerprintList {
  contract_version?: "1.0.0";
  page_info: PageInfo;
  repository: EntitySummary;
  snapshots: Array<RepositoryFingerprintSnapshot>;
}

export interface RepositoryFingerprintSnapshot {
  confidence: number;
  fact_id: string;
  fingerprint: string;
  observed_at: string;
  profile: Record<string, unknown>;
  source_revision: string;
  system_from: string;
  system_to?: string | null;
}

export interface RepositoryModernizationIntelligence {
  candidates: Array<ModernizationCandidateModel>;
  contract_version?: "1.0.0";
  repository: EntitySummary;
  source_revision?: string | null;
  truncated: boolean;
}

export interface RepositoryProfile {
  citations: Array<Citation>;
  components?: Array<string>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  descriptions?: Array<string>;
  key_files?: Array<string>;
  languages?: Array<string>;
  limitations?: Array<string>;
  operational_signals?: Array<string>;
  purpose?: string | null;
  purpose_source?: string | null;
  source_revision: string;
}

export interface RescanJob {
  completed_at?: string | null;
  connector_id?: string | null;
  created_at: string;
  id: string;
  last_error?: string | null;
  reason?: string;
  requested_by: string;
  started_at?: string | null;
  status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED";
}

export interface RescanJobList {
  contract_version?: "1.0.0";
  jobs: Array<RescanJob>;
  page_info: PageInfo;
}

export interface RescanRequest {
  connector_id?: string | null;
  idempotency_key: string;
  reason?: string;
}

export interface ResolutionCandidate {
  confidence: number;
  entity: EntitySummary;
  method: string;
}

export interface ResolvedEntity {
  entity: EntitySummary;
  matched_terms?: Array<string>;
  score: number;
}

export interface ReviewQueue {
  as_of: string;
  contract_version?: "1.0.0";
  counts: Record<string, number>;
  items: Array<ReviewQueueItem>;
  page_info: PageInfo;
}

export interface ReviewQueueItem {
  confidence: number;
  confidence_band: "HIGH" | "MEDIUM" | "LOW";
  created_at: string;
  item_id: string;
  item_type: "IDENTITY_ASSERTION" | "CAPABILITY_INFERENCE" | "DUPLICATE_CAPABILITY" | "MODERNIZATION_CANDIDATE" | "MODERNIZATION_RECOMMENDATION" | "APPLICATION_SIMILARITY";
  repository_id?: string | null;
  review_path: string;
  review_state: string;
  summary?: string | null;
  title: string;
  version: number;
}

export interface ScanPolicy {
  cadence: "HOURLY" | "DAILY" | "WEEKLY" | "MANUAL";
  contract_version?: "1.0.0";
  enabled: boolean;
  updated_at?: string | null;
  updated_by?: string | null;
}

export interface ScanPolicyUpdateRequest {
  cadence: "HOURLY" | "DAILY" | "WEEKLY" | "MANUAL";
  enabled?: boolean;
}

export interface ScanStatus {
  as_of: string;
  contract_version?: "1.0.0";
  policy: ScanPolicy;
  quotas: Array<ProviderQuota>;
  recent_jobs: Array<RescanJob>;
}

export interface Score {
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  method_version: string;
  value: number;
}

export interface SemanticSearchHit {
  entity: EntitySummary;
  excerpt?: string | null;
  input_hash: string;
  limitations?: Array<Record<string, unknown>>;
  matched_terms?: Array<string>;
  score: number;
  sensitivity: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED";
  source_fact_ids?: Array<string>;
}

export interface SemanticSearchRequest {
  entity_types?: Array<string>;
  limit?: number;
  min_score?: number;
  namespace?: Array<"BUSINESS" | "ENTERPRISE" | "TECHNOLOGY" | "OSS" | "DEPLOYMENT" | "INTELLIGENCE">;
  query: string;
}

export interface SemanticSearchResponse {
  as_of: string;
  contract_version?: "1.0.0";
  hits?: Array<SemanticSearchHit>;
  limitations?: Array<Record<string, unknown>>;
  model_or_algorithm: string;
  query_hash: string;
  space_id: string;
  space_key: string;
  template_version: string;
}

export interface ServiceControlRequest {
  desired_state: "RUNNING" | "STOPPED";
}

export interface ServiceStatus {
  category: "CORE" | "INGESTION" | "ENRICHMENT" | "GRAPH" | "INTELLIGENCE";
  configured?: boolean;
  controllable?: boolean;
  desired_state?: "RUNNING" | "STOPPED";
  detail?: string;
  failed?: number;
  key: string;
  last_activity_at?: string | null;
  last_heartbeat_at?: string | null;
  management_scope?: string;
  name: string;
  pending?: number;
  running?: number;
  state: "RUNNING" | "IDLE" | "WAITING" | "DEGRADED" | "OFFLINE" | "STOPPING" | "STOPPED";
}

export interface ServiceStatusList {
  as_of: string;
  contract_version?: "1.0.0";
  services: Array<ServiceStatus>;
}

export interface SessionInfo {
  actor_key: string;
  capabilities: Array<string>;
  contract_version?: "1.0.0";
  tenant_id?: string | null;
}

export interface SimulationCreateRequest {
  change_set_id: string;
  idempotency_key: string;
}

export interface SimulationFinding {
  affected_entity?: EntitySummary | null;
  classification: "DIRECT" | "TRANSITIVE" | "CONTEXT" | "STOP" | "INFORMATIONAL";
  confidence: number;
  detail: string;
  evidence_fact_ids?: Array<string>;
  id: string;
  path?: Array<EntitySummary>;
  rule_key: string;
  rule_version: string;
  severity: "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  title: string;
}

export interface SimulationInterpretation {
  cited_finding_ids?: Array<string>;
  explanation?: string | null;
  limitation?: string | null;
  quarantined_claims?: Array<QuarantinedClaim>;
  remediation?: Array<string>;
  risk?: string | null;
  rollout?: Array<string>;
  status: "AVAILABLE" | "UNAVAILABLE" | "QUARANTINED";
  verification?: Array<string>;
}

export interface SimulationRunModel {
  change_set_id: string;
  completed_at?: string | null;
  contract_version?: "1.0.0";
  created_at: string;
  estate_watermark: string;
  findings: Array<SimulationFinding>;
  gate: ChangeGate;
  id: string;
  interpretation: SimulationInterpretation;
  limitations: Array<GateReason>;
  policy_version: string;
  provider_version: string;
  replayed?: boolean;
  result_hash?: string | null;
  scanner_versions: Array<string>;
  started_at?: string | null;
  status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "LIMITED" | "NOT_SIMULATABLE" | "FAILED" | "CANCELLED";
}

export interface TargetCoverage {
  detail: string;
  registry_enumeration?: "AVAILABLE" | "NOT_COLLECTED";
  source: "ESTATE_OBSERVED" | "REGISTRY_ENUMERATED" | "MIXED";
}

export interface TaxonomySummary {
  key: string;
  name: string;
  summary?: string | null;
}

export interface TechnologyCatalogProfile {
  catalog_technology?: EntitySummary | null;
  category?: TaxonomySummary | null;
  citations: Array<Citation>;
  classification: "CURATED" | "CATALOG_MATCH" | "DETERMINISTIC" | "UNCLASSIFIED";
  dependents?: number | null;
  domain?: TaxonomySummary | null;
  ecosystem?: string | null;
  functions?: Array<TaxonomySummary>;
  homepage?: string | null;
  installation_command?: string | null;
  latest_version?: string | null;
  license?: string | null;
  package_name?: string | null;
  package_url?: string | null;
  repository_url?: string | null;
  summary?: string | null;
  versions?: number | null;
  weekly_downloads?: number | null;
}

export interface TechnologyDetail {
  alternatives?: Array<EntitySummary> | null;
  assessments: Array<AssessmentSummary>;
  catalog_profile?: TechnologyCatalogProfile | null;
  contract_version?: "1.0.0";
  freshness: Freshness;
  graph_intelligence?: EntityGraphIntelligence | null;
  internal_usage: InternalUsage;
  migration_patterns?: Array<EntitySummary> | null;
  packages: Array<EntitySummary>;
  projects: Array<EntitySummary>;
  recommendations: Array<RecommendationSummary>;
  registry_sources?: Array<PackageSource> | null;
  technology: EntitySummary;
}

export interface TechnologyEstateHierarchy {
  as_of: string;
  contract_version?: "1.0.0";
  nodes: Array<TechnologyEstateHierarchyNode>;
  truncated?: boolean;
}

export interface TechnologyEstateHierarchyNode {
  catalog_profile?: TechnologyCatalogProfile | null;
  citations: Array<Citation>;
  confidence: number;
  confidence_label: "HIGH" | "MEDIUM" | "LOW";
  dependent_applications: Array<EntitySummary>;
  depth: number;
  direct: boolean;
  parent_technology_id?: string | null;
  relationship: string;
  technology: EntitySummary;
}

export interface TenantCellPolicyModel {
  allowed_diversity?: number | null;
  allowed_technology_ids?: Array<string>;
  applicability?: "REQUIRED" | "RECOMMENDED" | "OPTIONAL" | "NOT_APPLICABLE";
  cell_key: string;
  discouraged_technology_ids?: Array<string>;
  effective_from?: string | null;
  effective_to?: string | null;
  exceptions?: Array<CanvasPolicyExceptionModel>;
  maximum_implementations?: number | null;
  minimum_implementations?: number | null;
  owner?: string | null;
  preferred_technology_ids?: Array<string>;
  prohibited_technology_ids?: Array<string>;
  rationale?: string;
  scope_selector?: CanvasScopeSelectorModel;
}

export interface TenantCodeFunctionPolicySummary {
  allowed_technology_ids: Array<string>;
  id: string;
  policy_fingerprint: string;
  prohibited_technology_ids: Array<string>;
  updated_at: string;
  updated_by: string;
}

export interface TenantCodeFunctionSummary {
  description: string;
  domain_key: string;
  function_key: string;
  name: string;
  policy?: TenantCodeFunctionPolicySummary | null;
  source: "PRIMARY" | "CUSTOM";
  status: "ACTIVE" | "RETIRED";
}

export interface TenantCodeFunctionUpsertRequest {
  allowed_technology_ids?: Array<string>;
  description?: string;
  domain_key: string;
  name: string;
  prohibited_technology_ids?: Array<string>;
  source: "PRIMARY" | "CUSTOM";
  status?: "ACTIVE" | "RETIRED";
}

export interface TenantCodePolicyState {
  available_technologies: Array<CodePolicyTechnologySummary>;
  contract_version?: "1.0.0";
  evaluations: Array<RepositoryCodePolicyEvaluation>;
  functions: Array<TenantCodeFunctionSummary>;
  policy_set_fingerprint: string;
  summary: TenantCodePolicySummary;
  technology_catalog_truncated?: boolean;
}

export interface TenantCodePolicySummary {
  compliant_repositories: number;
  custom_functions: number;
  evaluated_repositories: number;
  governed_functions: number;
  misaligned_repositories: number;
  stale_repositories: number;
}

export interface TenantExtensionCellModel {
  aspect_keys?: Array<string>;
  bindings: Array<CanvasBindingModel>;
  default_expectation: CellExpectationModel;
  definition: string;
  domain_key: "experience" | "application" | "integration" | "data" | "platform" | "delivery";
  key: string;
  label: string;
}

export interface TenantMember {
  actor_key: string;
  created_at: string;
  display_name?: string;
  email?: string;
  id: string;
  role: "view" | "review" | "execute" | "admin";
  status: "INVITED" | "ACTIVE" | "SUSPENDED";
  updated_at: string;
}

export interface TenantMemberList {
  contract_version?: "1.0.0";
  members: Array<TenantMember>;
}

export interface ValidationError {
  ctx?: Record<string, unknown>;
  input?: unknown;
  loc: Array<string | number>;
  msg: string;
  type: string;
}

export interface ValidTarget {
  canonical_key: string;
  entity_id: string;
  freshness: "FRESH" | "STALE" | "UNKNOWN";
  observed_at: string;
  observed_repository_count?: number;
  recommendation?: "CONSOLIDATE" | "CANDIDATE" | "LATEST_KNOWN" | "NONE";
  recommendation_detail?: string | null;
  source: string;
  support?: "SUPPORTED" | "UNKNOWN" | "UNSUPPORTED" | "END_OF_LIFE";
  version: string;
}

export interface ValidTargetList {
  contract_version?: "1.0.0";
  coverage?: TargetCoverage | null;
  limitations?: Array<GateReason>;
  page_info: PageInfo;
  policy_version: string;
  subject: EntitySummary;
  targets: Array<ValidTarget>;
}

export interface VersionDistribution {
  count: number;
  version: string;
}
