import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const source = path.join(repositoryRoot, "stackgraph-foundation/contracts/v1/openapi.json");
const output = path.join(repositoryRoot, "packages/shared/src/contracts/openapi.generated.ts");
const openapi = JSON.parse(fs.readFileSync(source, "utf8"));

const refName = (ref) => ref.split("/").at(-1);
const literal = (value) => JSON.stringify(value);

function typeFor(schema = {}) {
  if (schema.$ref) return refName(schema.$ref);
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ") || "never";
  if (schema.anyOf) return schema.anyOf.map(typeFor).join(" | ");
  if (schema.oneOf) return schema.oneOf.map(typeFor).join(" | ");
  if (schema.allOf) return schema.allOf.map(typeFor).join(" & ");
  if (schema.type === "array") return `Array<${typeFor(schema.items)}> ` .trim();
  if (schema.type === "object" || schema.properties || schema.additionalProperties) {
    if (!schema.properties) {
      return schema.additionalProperties === true
        ? "Record<string, unknown>"
        : `Record<string, ${typeFor(schema.additionalProperties)}> ` .trim();
    }
    const required = new Set(schema.required ?? []);
    const fields = Object.entries(schema.properties).map(([name, value]) => {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : literal(name);
      return `${key}${required.has(name) ? "" : "?"}: ${typeFor(value)};`;
    });
    if (schema.additionalProperties && schema.additionalProperties !== false) {
      fields.push(`[key: string]: ${schema.additionalProperties === true ? "unknown" : typeFor(schema.additionalProperties)};`);
    }
    return `{ ${fields.join(" ")} }`;
  }
  if (Array.isArray(schema.type)) return schema.type.map((type) => typeFor({ ...schema, type })).join(" | ");
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "null") return "null";
  return "unknown";
}

const schemas = openapi.components?.schemas ?? {};
const lines = [
  "// Generated by scripts/generate_contract_types.mjs from the canonical OpenAPI document.",
  "// Do not edit by hand. Run `pnpm contracts:generate`.",
  "",
];

for (const [name, schema] of Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b))) {
  if ((schema.type === "object" || schema.properties) && !schema.oneOf && !schema.anyOf && !schema.allOf) {
    const required = new Set(schema.required ?? []);
    lines.push(`export interface ${name} {`);
    for (const [property, value] of Object.entries(schema.properties ?? {})) {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(property) ? property : literal(property);
      lines.push(`  ${key}${required.has(property) ? "" : "?"}: ${typeFor(value)};`);
    }
    if (schema.additionalProperties && schema.additionalProperties !== false) {
      lines.push(`  [key: string]: ${schema.additionalProperties === true ? "unknown" : typeFor(schema.additionalProperties)};`);
    }
    lines.push("}", "");
  } else {
    lines.push(`export type ${name} = ${typeFor(schema)};`, "");
  }
}

fs.writeFileSync(output, lines.join("\n"));
